# Generated by Django 5.2.5 on 2025-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=50, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=50, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=50, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=50, verbose_name='Name (Russian)'),
        ),
    ]
