# Generated by Django 5.2.5 on 2025-11-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingstatus_name_de_bookingstatus_name_en_and_more'),
        ('providers', '0007_remove_provider_providers_p_address_e32109_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Location where the service is provided', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Location where the employee works', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use provider_location instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='providers.provider', verbose_name='Provider (Legacy)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use provider_location instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='providers.provider', verbose_name='Provider (Legacy)'),
        ),
    ]
