# Generated by Django 5.2.11 on 2026-03-11 11:34

import django.db.models.deletion
from datetime import time
from django.conf import settings
from django.db import migrations, models


def seed_booking_reference_data(apps, schema_editor):
    BookingStatus = apps.get_model('booking', 'BookingStatus')
    BookingCancellationReason = apps.get_model('booking', 'BookingCancellationReason')
    BookingAutoCompleteSettings = apps.get_model('booking', 'BookingAutoCompleteSettings')

    canonical_statuses = [
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]
    for code, name_en in canonical_statuses:
        BookingStatus.objects.update_or_create(
            name=code,
            defaults={'name_en': name_en},
        )
    BookingStatus.objects.exclude(name__in=[code for code, _ in canonical_statuses]).delete()

    default_reasons = [
        ('provider', 'client_no_show', 'Client did not arrive', 10),
        ('provider', 'provider_unavailable', 'Provider unavailable', 20),
        ('provider', 'service_not_possible', 'Service could not be delivered', 30),
        ('provider', 'duplicate_booking', 'Duplicate booking', 40),
        ('provider', 'technical_issue', 'Technical issue', 50),
        ('provider', 'other', 'Other', 60),
        ('client', 'changed_mind', 'Changed mind', 10),
        ('client', 'wrong_time', 'Wrong time', 20),
        ('client', 'no_longer_needed', 'No longer needed', 30),
        ('client', 'provider_problem', 'Provider problem', 40),
        ('client', 'client_refused_on_site', 'Client refused on site', 50),
        ('client', 'other', 'Other', 60),
    ]
    for scope, code, label, sort_order in default_reasons:
        BookingCancellationReason.objects.update_or_create(
            code=code,
            defaults={
                'scope': scope,
                'label': label,
                'sort_order': sort_order,
                'is_active': True,
            },
        )

    BookingAutoCompleteSettings.objects.get_or_create(
        id=1,
        defaults={
            'auto_complete_enabled': True,
            'auto_complete_days': 7,
            'service_periodicity_hours': 24,
            'service_start_time': time(3, 0),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_escort_owner_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], max_length=20, verbose_name='Scope')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Booking Cancellation Reason',
                'verbose_name_plural': 'Booking Cancellation Reasons',
                'ordering': ['scope', 'sort_order', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='bookingautocompletesettings',
            name='auto_complete_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.bookingcancellationreason', verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason_text',
            field=models.TextField(blank=True, help_text='Optional free-text explanation for cancellation', verbose_name='Cancellation Reason Text'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Provider')], help_text='Which side cancelled the booking', max_length=20, verbose_name='Cancelled By'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, help_text='User who recorded the cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_attendance',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('arrived', 'Arrived'), ('no_show', 'No show')], default='unknown', help_text='Whether the client arrived to the booking', max_length=20, verbose_name='Client Attendance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_by_actor',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('system', 'System')], help_text='Actor that completed the booking', max_length=20, verbose_name='Completed By Actor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_by_user',
            field=models.ForeignKey(blank=True, help_text='User who manually completed the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Completed By User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completion_reason_code',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto_timeout', 'Auto timeout')], help_text='How the booking was completed', max_length=20, verbose_name='Completion Reason Code'),
        ),
        migrations.AddField(
            model_name='bookingcancellation',
            name='cancelled_by_side',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Provider')], default='', max_length=20, verbose_name='Cancelled By Side'),
        ),
        migrations.AddField(
            model_name='bookingcancellation',
            name='client_attendance',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('arrived', 'Arrived'), ('no_show', 'No show')], default='unknown', max_length=20, verbose_name='Client Attendance'),
        ),
        migrations.AddField(
            model_name='bookingcancellation',
            name='reason_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_events', to='booking.bookingcancellationreason', verbose_name='Reason Code'),
        ),
        migrations.AlterField(
            model_name='bookingcancellation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='name',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50, unique=True, verbose_name='Status Name'),
        ),
        migrations.RunPython(seed_booking_reference_data, migrations.RunPython.noop),
    ]
