# Generated by Django 5.2.11 on 2026-03-11 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookingcancellationreason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingServiceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('service_not_provided', 'Service not provided')], default='service_not_provided', max_length=50, verbose_name='Issue Type')),
                ('reported_by_side', models.CharField(default='client', max_length=20, verbose_name='Reported By Side')),
                ('client_attendance_snapshot', models.CharField(choices=[('unknown', 'Unknown'), ('arrived', 'Arrived'), ('no_show', 'No show')], default='unknown', max_length=20, verbose_name='Client Attendance Snapshot')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20, verbose_name='Status')),
                ('resolution_outcome', models.CharField(blank=True, choices=[('provider_cancelled', 'Provider cancelled'), ('completed', 'Completed'), ('client_cancelled', 'Client cancelled'), ('claim_rejected', 'Claim rejected')], max_length=50, verbose_name='Resolution Outcome')),
                ('resolved_by_actor', models.CharField(blank=True, choices=[('provider', 'Provider'), ('support', 'Support'), ('system', 'System')], max_length=20, verbose_name='Resolved By Actor')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Resolution Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_issues', to='booking.booking', verbose_name='Booking')),
                ('reported_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_service_issues', to=settings.AUTH_USER_MODEL, verbose_name='Reported By User')),
                ('resolved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_service_issues', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By User')),
            ],
            options={
                'verbose_name': 'Booking Service Issue',
                'verbose_name_plural': 'Booking Service Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
