# Generated by Django 5.2.11 on 2026-03-17 14:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_source'),
        ('catalog', '0010_service_emergency_capability_mode_and_more'),
        ('pets', '0025_petdocument_addendum_and_type_contract'),
        ('providers', '0047_employeelocationrole_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10, verbose_name='Size Code')),
                ('owner_first_name', models.CharField(max_length=100, verbose_name='Owner First Name')),
                ('owner_last_name', models.CharField(max_length=100, verbose_name='Owner Last Name')),
                ('owner_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Owner Phone Number')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='Owner Email')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Pet Name')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Is Emergency')),
                ('source', models.CharField(choices=[('manual_entry', 'Manual entry')], default='manual_entry', max_length=32, verbose_name='Source')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('occupied_duration_minutes', models.PositiveIntegerField(verbose_name='Occupied Duration Minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Manual Booking Code')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('completed_by_actor', models.CharField(blank=True, choices=[('user', 'User'), ('system', 'System')], max_length=20, verbose_name='Completed By Actor')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('completion_reason_code', models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto_timeout', 'Auto timeout')], max_length=20, verbose_name='Completion Reason Code')),
                ('cancelled_by', models.CharField(blank=True, choices=[('client', 'Client'), ('provider', 'Provider')], max_length=20, verbose_name='Cancelled By')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason_text', models.TextField(blank=True, verbose_name='Cancellation Reason Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='pets.breed', verbose_name='Breed')),
                ('cancellation_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='booking.bookingcancellationreason', verbose_name='Cancellation Reason')),
                ('cancelled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_manual_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By User')),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_manual_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Completed By User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_manual_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='providers.employee', verbose_name='Employee')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='pets.pettype', verbose_name='Pet Type')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_bookings', to='providers.provider', verbose_name='Provider')),
                ('provider_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='providers.providerlocation', verbose_name='Provider Location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='catalog.service', verbose_name='Service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_manual_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Manual Booking',
                'verbose_name_plural': 'Manual Bookings',
                'ordering': ['-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManualVisitProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_family', models.CharField(choices=[('none', 'None'), ('veterinary', 'Veterinary')], default='veterinary', max_length=32, verbose_name='Protocol Family')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Next Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Anamnesis')),
                ('results', models.TextField(blank=True, verbose_name='Results')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommendations')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_manual_visit_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_visit_protocols', to='providers.employee', verbose_name='Employee')),
                ('manual_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_visit_protocol', to='booking.manualbooking', verbose_name='Manual Booking')),
                ('provider_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_visit_protocols', to='providers.providerlocation', verbose_name='Provider Location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_visit_protocols', to='catalog.service', verbose_name='Service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_manual_visit_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Manual Visit Protocol',
                'verbose_name_plural': 'Manual Visit Protocols',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderClientLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('normalized_phone_number', models.CharField(max_length=32, verbose_name='Normalized Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(choices=[('manual_booking', 'Manual booking')], default='manual_booking', max_length=32, verbose_name='Source')),
                ('invitation_status', models.CharField(choices=[('not_invited', 'Not invited'), ('invited', 'Invited'), ('registered', 'Registered')], default='not_invited', max_length=32, verbose_name='Invitation Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_leads', to='providers.provider', verbose_name='Provider')),
                ('provider_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_leads', to='providers.providerlocation', verbose_name='Provider Location')),
            ],
            options={
                'verbose_name': 'Provider Client Lead',
                'verbose_name_plural': 'Provider Client Leads',
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='manualbooking',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='booking.providerclientlead', verbose_name='Provider Client Lead'),
        ),
        migrations.AddIndex(
            model_name='providerclientlead',
            index=models.Index(fields=['provider', 'provider_location'], name='booking_pro_provide_c1d997_idx'),
        ),
        migrations.AddIndex(
            model_name='providerclientlead',
            index=models.Index(fields=['provider', 'normalized_phone_number'], name='booking_pro_provide_b88100_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerclientlead',
            constraint=models.UniqueConstraint(fields=('provider', 'normalized_phone_number'), name='unique_provider_manual_lead_phone'),
        ),
        migrations.AddIndex(
            model_name='manualbooking',
            index=models.Index(fields=['provider', 'start_time'], name='booking_man_provide_e3dac5_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbooking',
            index=models.Index(fields=['provider_location', 'start_time'], name='booking_man_provide_52f442_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbooking',
            index=models.Index(fields=['employee', 'start_time'], name='booking_man_employe_7436f6_idx'),
        ),
        migrations.AddIndex(
            model_name='manualbooking',
            index=models.Index(fields=['status', 'start_time'], name='booking_man_status_9cd476_idx'),
        ),
    ]
