# Generated by Django 5.2.11 on 2026-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_manualbooking_manualvisitprotocol_providerclientlead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingautocompletesettings',
            name='manual_booking_emergency_window_hours',
            field=models.PositiveIntegerField(default=4, help_text='Emergency manual booking is allowed only from now until now plus this number of hours.', verbose_name='Manual Booking Emergency Window (hours)'),
        ),
    ]
