# Generated by Django 5.2.5 on 2025-09-24 09:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeespecialization_description_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Optional. Unique phone number.', max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
