# Generated by Django 5.2.5 on 2025-09-27 12:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Required. Unique phone number for contact and verification.', max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
