# Generated by Django 5.2.5 on 2025-10-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'max_length': 'Username is too long.', 'unique': 'A user with that username already exists.'}, help_text='Auto-generated unique username for system compatibility.', max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
