# Generated by Django 5.2.5 on 2025-10-03 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_generate_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique token for password reset', max_length=64, unique=True, verbose_name='Reset Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time', verbose_name='Expires At')),
                ('used', models.BooleanField(default=False, help_text='Whether the token has been used', verbose_name='Used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True, verbose_name='Used At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request', null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_passw_token_b56ca3_idx'), models.Index(fields=['user', 'created_at'], name='users_passw_user_id_225c30_idx'), models.Index(fields=['expires_at'], name='users_passw_expires_853bc2_idx')],
            },
        ),
    ]
