# Generated by Django 5.2.5 on 2025-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('users', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, help_text='Service categories that the provider wants to offer', related_name='provider_forms', to='catalog.service', verbose_name='Selected Service Categories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_types',
            field=models.ManyToManyField(blank=True, help_text='Roles of the user in the system.', to='users.usertype', verbose_name='User Types'),
        ),
    ]
