# Generated by Django 5.2.5 on 2025-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_providerform_selected_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='provider_email',
            field=models.EmailField(blank=True, help_text='Email address of the provider (may differ from the applicant email)', max_length=254, null=True, verbose_name='Provider Email'),
        ),
    ]
