# Generated by Django 5.2.5 on 2025-11-12 17:30

from django.db import migrations, models


def fill_provider_email_from_creator(apps, schema_editor):
    """
    Заполняет provider_email для существующих записей значением created_by.email
    """
    ProviderForm = apps.get_model('users', 'ProviderForm')
    for form in ProviderForm.objects.filter(provider_email__isnull=True):
        if form.created_by and form.created_by.email:
            form.provider_email = form.created_by.email
            form.save(update_fields=['provider_email'])


def reverse_fill_provider_email(apps, schema_editor):
    """
    Обратная операция - не требуется, так как мы просто заполняем NULL значения
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_provider_email'),
    ]

    operations = [
        # Сначала заполняем provider_email для существующих записей
        migrations.RunPython(
            fill_provider_email_from_creator,
            reverse_fill_provider_email,
        ),
        # Затем делаем поле обязательным
        migrations.AlterField(
            model_name='providerform',
            name='provider_email',
            field=models.EmailField(
                help_text='Email address of the provider (may differ from the applicant email). Login credentials will be sent to this address upon approval.',
                verbose_name='Provider Email'
            ),
        ),
    ]
