# Generated by Django 5.2.5 on 2026-01-02 12:01

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_paymenthistory_invoice_and_more'),
        ('users', '0012_provideradmin_provider_roleinvite_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of registration. Required for regional addendums and VAT requirements.', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency for provider invoices (required)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_forms', to='billing.currency', verbose_name='Invoice Currency'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='offer_accepted',
            field=models.BooleanField(default=False, help_text='I have read and accepted the public offer (required)', verbose_name='Offer Accepted'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the offer was accepted', null=True, verbose_name='Offer Accepted At'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='offer_accepted_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which the offer was accepted', null=True, verbose_name='Offer Accepted IP'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='offer_accepted_user_agent',
            field=models.TextField(blank=True, help_text='User agent from which the offer was accepted', verbose_name='Offer Accepted User Agent'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Registration number (required). Format: letters, digits, spaces, hyphens. Minimum 3 characters.', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Registration number can only contain letters, digits, spaces, and hyphens.', regex='^[a-zA-Zа-яА-ЯёЁ0-9\\s-]+$'), django.core.validators.MinLengthValidator(3, message='Registration number must be at least 3 characters long.')], verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number / INN (required). Format: letters, digits, spaces, hyphens. Minimum 3 characters.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tax ID can only contain letters, digits, spaces, and hyphens.', regex='^[a-zA-Zа-яА-ЯёЁ0-9\\s-]+$'), django.core.validators.MinLengthValidator(3, message='Tax ID must be at least 3 characters long.')], verbose_name='Tax ID / INN'),
        ),
    ]
