# Generated by Django 5.2.5 on 2026-01-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_requisites_and_offer_to_provider_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for invoices (required)', max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='director_name',
            field=models.CharField(blank=True, help_text='Full name of director (for offer template substitution) (required)', max_length=200, verbose_name='Director Name'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN - required for EU/UA. For Russia, use "Account Number" field instead', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='is_vat_payer',
            field=models.BooleanField(default=False, help_text='Whether the organization is a VAT payer (required)', verbose_name='Is VAT Payer'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='kpp',
            field=models.CharField(blank=True, help_text='KPP (КПП) - required for Russian LLCs, hidden for other countries', max_length=20, verbose_name='KPP (Russia only)'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Type of organization: ИП, ООО, Corp, LLC, etc. (required)', max_length=50, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='swift_bic',
            field=models.CharField(blank=True, help_text='SWIFT / BIC - bank identifier (required)', max_length=11, verbose_name='SWIFT / BIC'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Number (EU VAT ID) - required for EU VAT payers. Format: PL12345678', max_length=50, verbose_name='VAT Number (EU VAT ID)'),
        ),
    ]
