# Generated by Django 5.2.10 on 2026-01-22 13:14

from django.db import migrations, models


def populate_admin_email_from_created_by(apps, schema_editor):
    """
    Заполняет admin_email значением created_by.email для существующих записей
    """
    ProviderForm = apps.get_model('users', 'ProviderForm')
    User = apps.get_model('users', 'User')
    for form in ProviderForm.objects.filter(admin_email__isnull=True):
        if form.created_by_id:
            try:
                creator = User.objects.get(id=form.created_by_id)
                form.admin_email = creator.email
                form.save(update_fields=['admin_email'])
            except User.DoesNotExist:
                pass


def reverse_populate_admin_email(apps, schema_editor):
    """
    Обратная миграция - не требуется, так как поле nullable
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_full_requisites_to_provider_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Email address of the registered user who will be appointed as provider administrator. The user must exist in the system. If not specified, will use the email of the user who created the form.', max_length=254, null=True, verbose_name='Admin Email'),
        ),
        migrations.RunPython(populate_admin_email_from_created_by, reverse_populate_admin_email),
        migrations.AlterField(
            model_name='providerform',
            name='kpp',
            field=models.CharField(blank=True, help_text='KPP (tax registration reason code) - required for Russian LLCs, hidden for other countries', max_length=20, verbose_name='KPP (Russia only)'),
        ),
        migrations.AlterField(
            model_name='providerform',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Type of organization: SP, OOO, Corp, LLC, etc. (required)', max_length=50, verbose_name='Organization Type'),
        ),
    ]
