# Generated by Django 5.2.10 on 2026-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_admin_email_to_provider_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_manual_override',
            field=models.BooleanField(default=False, help_text='Whether VAT ID was manually confirmed by administrator', verbose_name='VAT ID Manually Confirmed'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_result',
            field=models.JSONField(blank=True, help_text='Result of VAT ID verification from VIES API (company name, address, etc.)', null=True, verbose_name='VAT Verification Result'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('failed', 'Verification Failed')], default='pending', help_text='Status of VAT ID verification', max_length=20, verbose_name='VAT Verification Status'),
        ),
    ]
