# Generated by Django 5.2.10 on 2026-01-24 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_vat_verification_fields_to_provider_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_date',
            field=models.DateTimeField(blank=True, help_text='Date when VAT ID was verified via VIES API', null=True, verbose_name='VAT Verification Date'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_manual_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when VAT ID was manually confirmed', null=True, verbose_name='Manually Verified At'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_manual_by',
            field=models.ForeignKey(blank=True, help_text='User who manually confirmed VAT ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_verified_vat_forms', to=settings.AUTH_USER_MODEL, verbose_name='Manually Verified By'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='vat_verification_manual_comment',
            field=models.TextField(blank=True, help_text='Comment when manually confirming VAT ID (required if manually confirmed)', verbose_name='Manual Verification Comment'),
        ),
    ]
