# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_vat_verification_manual_fields_to_provider_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='address_components',
            field=models.JSONField(
                blank=True,
                help_text='Structured address from Google Places: formatted_address, street, house_number, city, postal_code, country, region.',
                null=True,
                verbose_name='Address components'
            ),
        ),
    ]
