# Generated by Django 5.2.10 on 2026-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_address_components_to_provider_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerform',
            name='documents',
            field=models.FileField(blank=True, help_text='Optional. If uploaded, we show consumers a "Documents available" badge and the documents on request.', null=True, upload_to='provider_docs/%Y/%m/%d/', verbose_name='Registration Documents'),
        ),
    ]
