# Generated by Django 5.2.10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_providerform_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFormDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='provider_docs/%Y/%m/%d/', verbose_name='Document File')),
                ('provider_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_documents', to='users.providerform', verbose_name='Provider Form')),
            ],
            options={
                'verbose_name': 'Provider form document',
                'verbose_name_plural': 'Provider form documents',
                'ordering': ['id'],
            },
        ),
    ]
