# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_providerformdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='language',
            field=models.CharField(
                blank=True,
                default='en',
                help_text='UI language of the user who submitted the form. Used for sending emails in that language.',
                max_length=10,
                verbose_name='Registration language'
            ),
        ),
    ]
