# Generated by Django 5.2.10 on 2026-02-15 11:42

from django.db import migrations, models


def set_owner_for_first_admin_per_provider(apps, schema_editor):
    """Для каждого провайдера первому по created_at админу выставляем role=owner."""
    ProviderAdmin = apps.get_model('users', 'ProviderAdmin')
    from django.db.models import Min
    first_ids = (
        ProviderAdmin.objects.values('provider_id')
        .annotate(min_created=Min('created_at'))
        .values_list('provider_id', 'min_created')
    )
    for provider_id, min_created in first_ids:
        ProviderAdmin.objects.filter(provider_id=provider_id, created_at=min_created).update(role='owner')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_providerform_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideradmin',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Provider manager'), ('provider_admin', 'Provider administrator')], default='provider_admin', help_text='Owner: one per provider (application author). Provider admin: can manage but not remove owner.', max_length=20, verbose_name='Role'),
        ),
        migrations.RunPython(set_owner_for_first_admin_per_provider, noop),
    ]
