# Generated by Django 5.2.10 on 2026-02-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0035_remove_employee_services'),
        ('users', '0023_provideradmin_three_roles_and_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideradmin',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('provider_manager', 'Provider manager'), ('provider_admin', 'Provider admin')], default='provider_admin', help_text='Owner / Provider manager / Provider admin. One user can have several roles per provider.', max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='UserScopeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('provider_manager', 'Provider manager'), ('provider_admin', 'Provider admin'), ('location_manager', 'Location manager'), ('service_worker', 'Service worker'), ('technical_worker', 'Technical worker')], max_length=24, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_roles', to='providers.providerlocation', verbose_name='Location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_roles', to='providers.provider', verbose_name='Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User scope role',
                'verbose_name_plural': 'User scope roles',
                'ordering': ['provider', 'location', 'role'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_usrscope_user_act_idx'), models.Index(fields=['provider', 'is_active'], name='users_usrscope_prov_act_idx'), models.Index(fields=['location', 'is_active'], name='users_usrscope_loc_act_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('user', 'provider', 'role'), name='users_userscoperole_provider_level_uniq'), models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('user', 'location', 'role'), name='users_userscoperole_location_level_uniq'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('location__isnull', True), ('role', 'owner')), fields=('provider',), name='users_userscoperole_one_owner_per_provider'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'location_manager')), fields=('location',), name='users_userscoperole_one_manager_per_location')],
            },
        ),
    ]
