# Generated by Django 5.2.10 on 2026-02-20 11:31

from django.db import migrations, models


def populate_owner_manager_from_admin(apps, schema_editor):
    """Для существующих заявок: заполняем owner_email и provider_manager_email из admin_email."""
    ProviderForm = apps.get_model('users', 'ProviderForm')
    for form in ProviderForm.objects.filter(owner_email__isnull=True).exclude(admin_email__isnull=True).exclude(admin_email=''):
        form.owner_email = form.admin_email
        form.save(update_fields=['owner_email'])
    for form in ProviderForm.objects.filter(provider_manager_email__isnull=True).exclude(admin_email__isnull=True).exclude(admin_email=''):
        form.provider_manager_email = form.admin_email
        form.save(update_fields=['provider_manager_email'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_provideradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email of the registered user who will be the provider owner. Required. The user must exist in the system.', max_length=254, null=True, verbose_name='Owner Email'),
        ),
        migrations.AddField(
            model_name='providerform',
            name='provider_manager_email',
            field=models.EmailField(blank=True, help_text='Email of the registered user who will be the provider manager. Required. The user must exist in the system. One person can be both owner and manager (same email).', max_length=254, null=True, verbose_name='Provider Manager Email'),
        ),
        migrations.AlterField(
            model_name='providerform',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Email of the registered user who will have access to the provider admin application. Required. The user must exist in the system. One person can combine owner/manager/admin (same email in several fields).', max_length=254, null=True, verbose_name='Administrator with access to provider admin panel'),
        ),
        migrations.RunPython(populate_owner_manager_from_admin, noop),
    ]
