# Generated by Django 5.2.10 on 2026-02-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_add_owner_and_provider_manager_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleInvite',
        ),
    ]
