# Generated by Django 5.2.11 on 2026-04-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_fix_project_auth_user_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='Whether the user has confirmed ownership of the email address.', verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the email address was confirmed.', null=True, verbose_name='Email Verified At'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique token for email verification', max_length=64, unique=True, verbose_name='Verification Token')),
                ('sent_to_email', models.EmailField(blank=True, help_text='Email address used for the verification message', max_length=254, verbose_name='Sent To Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time', verbose_name='Expires At')),
                ('used', models.BooleanField(default=False, help_text='Whether the token has been used', verbose_name='Used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True, verbose_name='Used At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_email_token_c6eae7_idx'), models.Index(fields=['user', 'created_at'], name='users_email_user_id_0b55cf_idx'), models.Index(fields=['expires_at'], name='users_email_expires_7cc044_idx')],
            },
        ),
    ]
