# Generated by Django 5.2.11 on 2026-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('me', 'Montenegrin'), ('de', 'German')], default='en', help_text='Preferred UI and notification language for the user.', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
