BOOKING_STATUS_ACTIVE = 'active'
BOOKING_STATUS_COMPLETED = 'completed'
BOOKING_STATUS_CANCELLED = 'cancelled'

CANONICAL_BOOKING_STATUS_NAMES = (
    BOOKING_STATUS_ACTIVE,
    BOOKING_STATUS_COMPLETED,
    BOOKING_STATUS_CANCELLED,
)

ACTIVE_BOOKING_STATUS_NAMES = (BOOKING_STATUS_ACTIVE,)

CANCELLED_BY_CLIENT = 'client'
CANCELLED_BY_PROVIDER = 'provider'
CANCELLATION_SIDE_CHOICES = (
    (CANCELLED_BY_CLIENT, 'Client'),
    (CANCELLED_BY_PROVIDER, 'Provider'),
)

COMPLETED_BY_USER = 'user'
COMPLETED_BY_SYSTEM = 'system'
COMPLETION_ACTOR_CHOICES = (
    (COMPLETED_BY_USER, 'User'),
    (COMPLETED_BY_SYSTEM, 'System'),
)

COMPLETION_REASON_MANUAL = 'manual'
COMPLETION_REASON_AUTO_TIMEOUT = 'auto_timeout'
COMPLETION_REASON_CHOICES = (
    (COMPLETION_REASON_MANUAL, 'Manual'),
    (COMPLETION_REASON_AUTO_TIMEOUT, 'Auto timeout'),
)

CLIENT_ATTENDANCE_UNKNOWN = 'unknown'
CLIENT_ATTENDANCE_ARRIVED = 'arrived'
CLIENT_ATTENDANCE_NO_SHOW = 'no_show'
CLIENT_ATTENDANCE_CHOICES = (
    (CLIENT_ATTENDANCE_UNKNOWN, 'Unknown'),
    (CLIENT_ATTENDANCE_ARRIVED, 'Arrived'),
    (CLIENT_ATTENDANCE_NO_SHOW, 'No show'),
)

CANCELLATION_REASON_CLIENT_NO_SHOW = 'client_no_show'
CANCELLATION_REASON_PROVIDER_UNAVAILABLE = 'provider_unavailable'
CANCELLATION_REASON_SERVICE_NOT_POSSIBLE = 'service_not_possible'
CANCELLATION_REASON_DUPLICATE_BOOKING = 'duplicate_booking'
CANCELLATION_REASON_TECHNICAL_ISSUE = 'technical_issue'
CANCELLATION_REASON_CHANGED_MIND = 'changed_mind'
CANCELLATION_REASON_WRONG_TIME = 'wrong_time'
CANCELLATION_REASON_NO_LONGER_NEEDED = 'no_longer_needed'
CANCELLATION_REASON_PROVIDER_PROBLEM = 'provider_problem'
CANCELLATION_REASON_CLIENT_REFUSED_ON_SITE = 'client_refused_on_site'
CANCELLATION_REASON_OTHER = 'other'

REPORTED_BY_CLIENT = 'client'
BOOKING_SERVICE_ISSUE_REPORT_WINDOW_DAYS = 7

ISSUE_TYPE_SERVICE_NOT_PROVIDED = 'service_not_provided'
ISSUE_TYPE_CHOICES = (
    (ISSUE_TYPE_SERVICE_NOT_PROVIDED, 'Service not provided'),
)

ISSUE_STATUS_OPEN = 'open'
ISSUE_STATUS_ACKNOWLEDGED = 'acknowledged'
ISSUE_STATUS_RESOLVED = 'resolved'
ISSUE_STATUS_REJECTED = 'rejected'
ISSUE_STATUS_CHOICES = (
    (ISSUE_STATUS_OPEN, 'Open'),
    (ISSUE_STATUS_ACKNOWLEDGED, 'Acknowledged'),
    (ISSUE_STATUS_RESOLVED, 'Resolved'),
    (ISSUE_STATUS_REJECTED, 'Rejected'),
)

RESOLUTION_OUTCOME_PROVIDER_CANCELLED = 'provider_cancelled'
RESOLUTION_OUTCOME_COMPLETED = 'completed'
RESOLUTION_OUTCOME_CLIENT_CANCELLED = 'client_cancelled'
RESOLUTION_OUTCOME_CLAIM_REJECTED = 'claim_rejected'
RESOLUTION_OUTCOME_CHOICES = (
    (RESOLUTION_OUTCOME_PROVIDER_CANCELLED, 'Provider cancelled'),
    (RESOLUTION_OUTCOME_COMPLETED, 'Completed'),
    (RESOLUTION_OUTCOME_CLIENT_CANCELLED, 'Client cancelled'),
    (RESOLUTION_OUTCOME_CLAIM_REJECTED, 'Claim rejected'),
)

RESOLVED_BY_PROVIDER = 'provider'
RESOLVED_BY_SUPPORT = 'support'
RESOLVED_BY_SYSTEM = 'system'
RESOLUTION_ACTOR_CHOICES = (
    (RESOLVED_BY_PROVIDER, 'Provider'),
    (RESOLVED_BY_SUPPORT, 'Support'),
    (RESOLVED_BY_SYSTEM, 'System'),
)
