# Generated by Django 5.2.11 on 2026-05-14 06:32

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='PetCare', help_text='Main product brand shown in user-facing interfaces', max_length=120, verbose_name='Product name')),
                ('short_name', models.CharField(default='PetCare', help_text='Short brand name for compact UI areas', max_length=60, verbose_name='Short name')),
                ('public_site_title', models.CharField(default='PetsCare', help_text='Browser title for the public frontend', max_length=160, verbose_name='Public site title')),
                ('provider_admin_site_title', models.CharField(default='PetCare - Provider Admin', help_text='Browser title for the provider admin frontend', max_length=160, verbose_name='Provider admin site title')),
                ('legal_footer_name', models.CharField(default='PetCare', help_text='Name used in legal footer copy', max_length=160, verbose_name='Legal footer name')),
                ('support_email', models.EmailField(default='support@petcare.com', help_text='Support email used by public contact forms and links', max_length=254, verbose_name='Support email')),
                ('support_phone', models.CharField(blank=True, default='+1 (555) 123-4567', help_text='Support phone shown on public contact pages', max_length=64, verbose_name='Support phone')),
                ('contact_path', models.CharField(default='/contact', help_text='Public contact page path', max_length=120, verbose_name='Contact path')),
                ('logo', models.ImageField(blank=True, help_text='Optional brand logo', null=True, upload_to='branding/logos/%Y/%m/%d/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Optional browser favicon', null=True, upload_to='branding/favicons/%Y/%m/%d/', verbose_name='Favicon')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branding profile is used by frontends', verbose_name='Is active')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version for concurrent edits', verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these branding settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_platform_branding_settings', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Platform Branding Settings',
                'verbose_name_plural': 'Platform Branding Settings',
                'db_table': 'platform_branding_settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformBrandingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('public', 'Public frontend'), ('provider_admin', 'Provider admin frontend')], default='public', max_length=32, verbose_name='App type')),
                ('scheme', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=8, verbose_name='Scheme')),
                ('domain', models.CharField(help_text='Domain without scheme or path, for example example.com', max_length=253, verbose_name='Domain')),
                ('base_path', models.CharField(default='/', help_text='Path where the frontend is mounted', max_length=120, verbose_name='Base path')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this frontend', verbose_name='Is primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='system_settings.platformbrandingsettings', verbose_name='Branding settings')),
            ],
            options={
                'verbose_name': 'Platform Branding Domain',
                'verbose_name_plural': 'Platform Branding Domains',
                'db_table': 'platform_branding_domains',
                'ordering': ['app_type', '-is_primary', 'display_order', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='RatingDecaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_life_days', models.PositiveIntegerField(default=365, help_text='Period after which review weight is halved (30-1825 days)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1825)], verbose_name='Half-life period (days)')),
                ('min_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Minimum weight for old reviews (0.01-1.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)], verbose_name='Minimum weight')),
                ('max_age_days', models.PositiveIntegerField(default=1095, help_text='Maximum age of reviews to consider (90-3650 days)', validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(3650)], verbose_name='Maximum age (days)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these settings are currently active', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Rating Decay Settings',
                'verbose_name_plural': 'Rating Decay Settings',
                'db_table': 'rating_decay_settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_min_length', models.PositiveIntegerField(default=12, help_text='Minimum password length (8-128 characters)', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(128)], verbose_name='Minimum password length')),
                ('password_require_uppercase', models.BooleanField(default=True, help_text='Password must contain at least one uppercase letter', verbose_name='Require uppercase letters')),
                ('password_require_lowercase', models.BooleanField(default=True, help_text='Password must contain at least one lowercase letter', verbose_name='Require lowercase letters')),
                ('password_require_numbers', models.BooleanField(default=True, help_text='Password must contain at least one number', verbose_name='Require numbers')),
                ('password_require_special_chars', models.BooleanField(default=True, help_text='Password must contain at least one special character', verbose_name='Require special characters')),
                ('password_max_age_days', models.PositiveIntegerField(default=90, help_text='Days after which password must be changed (30-365)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)], verbose_name='Password maximum age (days)')),
                ('password_history_count', models.PositiveIntegerField(default=5, help_text='Number of previous passwords that cannot be reused', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Password history count')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=1440, help_text='Session timeout in minutes (15-10080)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(10080)], verbose_name='Session timeout (minutes)')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=3, help_text='Maximum number of concurrent sessions per user', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Maximum concurrent sessions')),
                ('force_logout_on_password_change', models.BooleanField(default=True, help_text='Automatically logout all sessions when password is changed', verbose_name='Force logout on password change')),
                ('session_inactivity_timeout_minutes', models.PositiveIntegerField(default=30, help_text='Logout user after inactivity period (5-480 minutes)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='Session inactivity timeout (minutes)')),
                ('rate_limiting_enabled', models.BooleanField(default=True, help_text='Enable rate limiting for API requests and login attempts', verbose_name='Enable rate limiting')),
                ('login_attempts_per_hour', models.PositiveIntegerField(default=5, help_text='Maximum login attempts per hour per IP', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Login attempts per hour')),
                ('api_requests_per_minute', models.PositiveIntegerField(default=60, help_text='Maximum API requests per minute per user', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='API requests per minute')),
                ('brute_force_lockout_minutes', models.PositiveIntegerField(default=15, help_text='Account lockout duration after failed attempts', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Brute force lockout (minutes)')),
                ('ip_restrictions_enabled', models.BooleanField(default=False, help_text='Enable IP whitelist/blacklist restrictions', verbose_name='Enable IP restrictions')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = allow all)', verbose_name='IP whitelist')),
                ('ip_blacklist', models.JSONField(blank=True, default=list, help_text='List of blocked IP addresses', verbose_name='IP blacklist')),
                ('audit_logging_enabled', models.BooleanField(default=True, help_text='Enable comprehensive audit logging', verbose_name='Enable audit logging')),
                ('audit_log_retention_days', models.PositiveIntegerField(default=365, help_text='How long to keep audit logs (30-2555 days)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(2555)], verbose_name='Audit log retention (days)')),
                ('log_sensitive_data', models.BooleanField(default=False, help_text='Log sensitive data in audit trails (use with caution)', verbose_name='Log sensitive data')),
                ('log_failed_login_attempts', models.BooleanField(default=True, help_text='Log all failed login attempts for security monitoring', verbose_name='Log failed login attempts')),
                ('require_https', models.BooleanField(default=True, help_text='Require HTTPS for all connections', verbose_name='Require HTTPS')),
                ('enable_csrf_protection', models.BooleanField(default=True, help_text='Enable Cross-Site Request Forgery protection', verbose_name='Enable CSRF protection')),
                ('enable_xss_protection', models.BooleanField(default=True, help_text='Enable Cross-Site Scripting protection headers', verbose_name='Enable XSS protection')),
                ('enable_content_security_policy', models.BooleanField(default=True, help_text='Enable Content Security Policy headers', verbose_name='Enable Content Security Policy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
                'db_table': 'security_settings',
            },
        ),
        migrations.CreateModel(
            name='BlockingScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these schedule settings are currently active', verbose_name='Is active')),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Interval')], default='daily', help_text='Frequency of blocking checks', max_length=20, verbose_name='Frequency')),
                ('check_time', models.TimeField(default=datetime.time(2, 0), help_text='Time of day to perform checks (HH:MM format)', verbose_name='Check Time')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Days of week for weekly frequency (0=Monday, 6=Sunday). Empty = all days.', verbose_name='Days of Week')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly frequency (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of Month')),
                ('custom_interval_hours', models.PositiveIntegerField(blank=True, help_text='Custom interval in hours for custom frequency (1-8760 hours)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8760)], verbose_name='Custom Interval (Hours)')),
                ('exclude_weekends', models.BooleanField(default=False, help_text='Skip checks on weekends (Saturday and Sunday)', verbose_name='Exclude Weekends')),
                ('exclude_holidays', models.BooleanField(default=False, help_text='Skip checks on holidays (requires holiday calendar)', verbose_name='Exclude Holidays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blocking_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Blocking Schedule Settings',
                'verbose_name_plural': 'Blocking Schedule Settings',
                'db_table': 'blocking_schedule_settings',
                'ordering': ['-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_blocking_schedule')],
            },
        ),
        migrations.AddConstraint(
            model_name='platformbrandingsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_platform_branding_settings'),
        ),
        migrations.AddConstraint(
            model_name='platformbrandingdomain',
            constraint=models.UniqueConstraint(fields=('branding', 'app_type', 'domain', 'base_path'), name='unique_platform_branding_domain'),
        ),
        migrations.AddConstraint(
            model_name='platformbrandingdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('branding', 'app_type'), name='unique_primary_platform_branding_domain'),
        ),
    ]
