# Generated by Django 5.2.11 on 2026-05-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_seed_current_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('contact_form', 'Contact form'), ('email', 'Email'), ('phone', 'Phone call'), ('admin', 'Admin entry')], default='contact_form', help_text='How this support request was received', max_length=32, verbose_name='Source')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('waiting_customer', 'Waiting for customer'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', help_text='Current support workflow status', max_length=32, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16, verbose_name='Priority')),
                ('subject', models.CharField(help_text='Short summary of the support request', max_length=200, verbose_name='Subject')),
                ('message', models.TextField(help_text='Full support request text', verbose_name='Message')),
                ('author_name', models.CharField(blank=True, max_length=160, verbose_name='Author name')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Author email')),
                ('author_phone', models.CharField(blank=True, max_length=64, verbose_name='Author phone')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status changed at')),
                ('language', models.CharField(blank=True, help_text='Language selected in the public frontend', max_length=16, verbose_name='Language')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='Page URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes visible only in Django admin', verbose_name='Admin notes')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version for concurrent edits', verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.ForeignKey(blank=True, help_text='Registered user who sent the request, if known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who manually created the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('handler', models.ForeignKey(blank=True, help_text='Support team member responsible for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Handler')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Status changed by')),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'db_table': 'support_requests',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', 'priority', '-created_at'], name='support_req_status_idx'), models.Index(fields=['source', '-created_at'], name='support_req_source_idx'), models.Index(fields=['handler', 'status'], name='support_req_handler_idx')],
            },
        ),
    ]
