# Generated by Django 5.2.11 on 2026-03-19 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='cancellations_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Weight of cancellations in rating calculation (0-1)', max_digits=3, verbose_name='Cancellations Weight'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='no_show_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Weight of no-show in rating calculation (0-1)', max_digits=3, verbose_name='No Show Weight'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviews_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Weight of reviews in rating calculation (0-1)', max_digits=3, verbose_name='Reviews Weight'),
        ),
    ]
