# Generated by Django 5.2.5 on 2025-09-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='users.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='searchradius',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_radius', to='users.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='users.user', verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='addressvalidation',
            index=models.Index(fields=['address', 'created_at'], name='geolocation_address_9799e9_idx'),
        ),
        migrations.AddIndex(
            model_name='addressvalidation',
            index=models.Index(fields=['is_valid'], name='geolocation_is_vali_c1a6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['point'], name='idx_location_point'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['point'], name='idx_location_history_point'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['created_at'], name='idx_location_history_created'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['point'], name='idx_user_location_point'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['last_updated'], name='idx_user_location_updated'),
        ),
    ]
