# Generated by Django 5.2.5 on 2025-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_alter_address_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Legacy field for backward compatibility', verbose_name='Is Validated'),
        ),
    ]
