# Generated by Django 5.2.5 on 2025-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_address_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
