# Generated by Django 5.2.10 on 2026-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0005_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_geocoded',
            field=models.BooleanField(default=False, verbose_name='Is Geocoded'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Is Valid'),
        ),
    ]
