# Generated by Django 5.2.10 on 2026-02-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('country', models.CharField(choices=[('RU', 'Russia'), ('UA', 'Ukraine'), ('ME', 'Montenegro'), ('RS', 'Serbia'), ('DE', 'Germany'), ('FR', 'France'), ('US', 'United States')], db_index=True, max_length=2, verbose_name='Country')),
                ('day_type', models.CharField(choices=[('WORKING', 'Working day'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Public holiday'), ('SHORT_DAY', 'Short day (pre-holiday)')], default='WORKING', max_length=20, verbose_name='Day type')),
                ('is_transfer', models.BooleanField(default=False, help_text='True if this is a working Saturday transferred from another date (e.g. RU).', verbose_name='Is transfer')),
                ('description', models.CharField(blank=True, help_text='E.g. "New Year", "Transfer from May 2".', max_length=255, verbose_name='Description')),
                ('is_manually_corrected', models.BooleanField(default=False, help_text='If True, sync scripts must NOT overwrite this record.', verbose_name='Manually corrected')),
            ],
            options={
                'verbose_name': 'Production calendar day',
                'verbose_name_plural': 'Production calendar',
                'ordering': ['date', 'country'],
                'constraints': [models.UniqueConstraint(fields=('date', 'country'), name='production_calendar_date_country_uniq')],
            },
        ),
    ]
