# Generated by Django 5.2.5 on 2025-11-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('providers', '0007_remove_provider_providers_p_address_e32109_idx_and_more'),
        ('scheduling', '0002_workplace_name_de_workplace_name_en_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepriority',
            unique_together={('provider', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='staffingrequirement',
            unique_together={('provider', 'service', 'day_of_week')},
        ),
        migrations.AddField(
            model_name='servicepriority',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Location this priority applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_priorities', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AddField(
            model_name='staffingrequirement',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Location this requirement applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Location this workplace belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AlterField(
            model_name='servicepriority',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use provider_location instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_priorities', to='providers.provider', verbose_name='Provider (Legacy)'),
        ),
        migrations.AlterField(
            model_name='staffingrequirement',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use provider_location instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='providers.provider', verbose_name='Provider (Legacy)'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use provider_location instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='providers.provider', verbose_name='Provider (Legacy)'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepriority',
            unique_together={('provider', 'service'), ('provider_location', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='staffingrequirement',
            unique_together={('provider', 'service', 'day_of_week'), ('provider_location', 'service', 'day_of_week')},
        ),
    ]
