# Generated by Django 5.2.11 on 2026-02-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0047_employeelocationrole_end_date_and_more'),
        ('scheduling', '0005_alter_servicepriority_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Optional: specific location for this absence. If null, applies to all locations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Optional: specific location for this absence. If null, applies to all locations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Optional: specific location for this absence. If null, applies to all locations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
    ]
