# Generated by Django 5.2.11 on 2026-02-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_dayoff_provider_location_sickleave_provider_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayOff',
        ),
    ]
