# Generated by Django 5.2.5 on 2025-09-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('geolocation', '0002_initial'),
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='employeeprovider',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprovider_set', to='providers.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeworkslot',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_slots', to='providers.employee'),
        ),
        migrations.AddField(
            model_name='managertransferinvite',
            name='from_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_manager_invites', to='providers.employee', verbose_name='From manager'),
        ),
        migrations.AddField(
            model_name='managertransferinvite',
            name='to_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_manager_invites', to='providers.employee', verbose_name='To employee'),
        ),
        migrations.AddField(
            model_name='provider',
            name='available_category_levels',
            field=models.ManyToManyField(help_text='Category levels available for this provider', related_name='available_providers', to='catalog.service', verbose_name='Available Category Levels'),
        ),
        migrations.AddField(
            model_name='provider',
            name='structured_address',
            field=models.ForeignKey(blank=True, help_text='Structured address with validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='geolocation.address', verbose_name='Structured Address'),
        ),
        migrations.AddField(
            model_name='managertransferinvite',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='employeeprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprovider_set', to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='employeejoinrequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='employee',
            name='providers',
            field=models.ManyToManyField(help_text='Providers this employee works for', related_name='employees', through='providers.EmployeeProvider', to='providers.provider', verbose_name='Providers'),
        ),
        migrations.AddField(
            model_name='providerschedule',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='provider',
            field=models.ForeignKey(help_text='Provider offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='service',
            field=models.ForeignKey(help_text='Service being offered', on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to='catalog.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(help_text='Employee this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='providers.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_patterns', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='patternday',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='providers.schedulepattern'),
        ),
        migrations.AddIndex(
            model_name='employeeworkslot',
            index=models.Index(fields=['date'], name='providers_e_date_50b6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeworkslot',
            index=models.Index(fields=['slot_type'], name='providers_e_slot_ty_991b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='providers_p_name_44a164_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['address'], name='providers_p_address_e32109_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['rating'], name='providers_p_rating_f70abf_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active'], name='providers_p_is_acti_7dfa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['point'], name='idx_provider_point'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['exclude_from_blocking_checks'], name='providers_p_exclude_a66663_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='managertransferinvite',
            unique_together={('to_employee', 'provider', 'is_accepted', 'is_declined')},
        ),
        migrations.AddIndex(
            model_name='employeeprovider',
            index=models.Index(fields=['start_date'], name='providers_e_start_d_a9c586_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprovider',
            index=models.Index(fields=['end_date'], name='providers_e_end_dat_7de925_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprovider',
            index=models.Index(fields=['is_confirmed'], name='providers_e_is_conf_401368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprovider',
            unique_together={('employee', 'provider', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='employeejoinrequest',
            index=models.Index(fields=['status'], name='providers_e_status_eb6423_idx'),
        ),
        migrations.AddIndex(
            model_name='employeejoinrequest',
            index=models.Index(fields=['created_at'], name='providers_e_created_303cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='providers_e_positio_895454_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='providers_e_is_acti_53dce3_idx'),
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['weekday'], name='providers_p_weekday_553472_idx'),
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['is_closed'], name='providers_p_is_clos_49f3ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerschedule',
            unique_together={('provider', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['provider', 'service'], name='providers_p_provide_df7ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['is_active'], name='providers_p_is_acti_4f83ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerservice',
            unique_together={('provider', 'service')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day_of_week'], name='providers_s_day_of__028d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_working'], name='providers_s_is_work_eb2286_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('employee', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='schedulepattern',
            index=models.Index(fields=['name'], name='providers_s_name_13516a_idx'),
        ),
        migrations.AddIndex(
            model_name='patternday',
            index=models.Index(fields=['weekday'], name='providers_p_weekday_17175f_idx'),
        ),
        migrations.AddIndex(
            model_name='patternday',
            index=models.Index(fields=['is_day_off'], name='providers_p_is_day__3edaf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patternday',
            unique_together={('pattern', 'weekday')},
        ),
    ]
