# Generated by Django 5.2.5 on 2025-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepattern',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description in German', verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description in English', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='description_me',
            field=models.TextField(blank=True, help_text='Description in Montenegrian', verbose_name='Description (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Description in Russian', verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=100, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=100, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=100, verbose_name='Name (Russian)'),
        ),
    ]
