# Generated by Django 5.2.5 on 2025-10-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_schedulepattern_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='provider',
            name='idx_provider_point',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='point',
        ),
    ]
