# Generated by Django 5.2.5 on 2025-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_remove_provider_idx_provider_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(help_text='Contact email', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=20, unique=True, verbose_name='Phone Number'),
        ),
    ]
