# Generated by Django 5.2.5 on 2025-11-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('geolocation', '0005_address_latitude_address_longitude'),
        ('providers', '0005_alter_provider_email_alter_provider_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this location (e.g., "Branch on Timiryazevskaya")', max_length=200, verbose_name='Location Name')),
                ('phone_number', models.CharField(help_text='Contact phone number for this location (not unique)', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Contact email for this location (not unique)', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(help_text='Organization this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='providers.Provider', verbose_name='Provider Organization')),
                ('structured_address', models.ForeignKey(blank=True, help_text='Structured address with validation and coordinates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_locations', to='geolocation.address', verbose_name='Structured Address')),
            ],
            options={
                'verbose_name': 'Provider Location',
                'verbose_name_plural': 'Provider Locations',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderLocationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the service at this location', max_digits=10, verbose_name='Price')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the service in minutes for this location', verbose_name='Duration In Minutes')),
                ('tech_break_minutes', models.PositiveIntegerField(default=0, help_text='Technical break time in minutes after the service (for cleaning, preparation, etc.)', verbose_name='Technical Break Minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available at this location', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('location', models.ForeignKey(help_text='Location offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='providers.providerlocation', verbose_name='Location')),
                ('service', models.ForeignKey(help_text='Service being offered at this location', on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='catalog.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Provider Location Service',
                'verbose_name_plural': 'Provider Location Services',
                'ordering': ['location', 'service'],
            },
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='available_services',
            field=models.ManyToManyField(help_text="Services available at this location. Must be from provider's level 0 categories.", related_name='locations', through='providers.ProviderLocationService', to='catalog.service', verbose_name='Available Services'),
        ),
        migrations.AddIndex(
            model_name='providerlocationservice',
            index=models.Index(fields=['location', 'service'], name='providers_p_locatio_9d4b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='providerlocationservice',
            index=models.Index(fields=['is_active'], name='providers_p_is_acti_7aeb84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerlocationservice',
            unique_together={('location', 'service')},
        ),
        migrations.AddIndex(
            model_name='providerlocation',
            index=models.Index(fields=['provider', 'is_active'], name='providers_p_provide_00e2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='providerlocation',
            index=models.Index(fields=['is_active'], name='providers_p_is_acti_ab3582_idx'),
        ),
    ]
