# Generated by Django 5.2.5 on 2025-11-13 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('geolocation', '0005_address_latitude_address_longitude'),
        ('providers', '0006_providerlocation_providerlocationservice_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='provider',
            name='providers_p_address_e32109_idx',
        ),
        migrations.RemoveIndex(
            model_name='provider',
            name='providers_p_rating_f70abf_idx',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='rating',
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account number (unique, one account = one organization)', max_length=50, null=True, unique=True, verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_address',
            field=models.TextField(blank=True, help_text='Bank address (optional)', verbose_name='Bank Address'),
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_bik',
            field=models.CharField(blank=True, help_text='Bank identification code (BIK)', max_length=20, verbose_name='Bank BIK'),
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank', max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='correspondent_account',
            field=models.CharField(blank=True, help_text='Correspondent account number', max_length=50, verbose_name='Correspondent Account'),
        ),
        migrations.AddField(
            model_name='provider',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Registration number (unique, required for approval)', max_length=100, null=True, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='provider',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number / INN (unique, required for approval)', max_length=50, null=True, unique=True, verbose_name='Tax ID / INN'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='available_category_levels',
            field=models.ManyToManyField(help_text='Category levels (level 0) available for this organization', related_name='available_providers', to='catalog.service', verbose_name='Available Category Levels'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(help_text='Main contact email of the organization (unique)', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the organization is currently active', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='providers/logos/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Name of the organization (unique)', max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(help_text='Main contact phone number of the organization (unique)', max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='structured_address',
            field=models.ForeignKey(blank=True, help_text='Legal address of the organization (for documents, contracts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='geolocation.address', verbose_name='Structured Address'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, help_text='Organization website', verbose_name='Website'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['tax_id'], name='providers_p_tax_id_0d7a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['registration_number'], name='providers_p_registr_786c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['bank_account'], name='providers_p_bank_ac_31f7c1_idx'),
        ),
    ]
