# Generated by Django 5.2.5 on 2025-11-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_remove_provider_providers_p_address_e32109_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='provider',
            name='providers_p_bank_ac_31f7c1_idx',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bank_bik',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='correspondent_account',
        ),
    ]
