# Generated by Django 5.2.5 on 2025-11-13 17:00

from django.db import migrations, models
import django.db.models.deletion


def delete_all_schedules(apps, schema_editor):
    """
    Удаляет все записи Schedule перед добавлением обязательного поля provider_location.
    База очищена, но на всякий случай удаляем все записи.
    """
    Schedule = apps.get_model('providers', 'Schedule')
    Schedule.objects.all().delete()


def reverse_delete_all_schedules(apps, schema_editor):
    """
    Обратная операция - не требуется, так как мы просто удаляем записи.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_remove_provider_providers_p_bank_ac_31f7c1_idx_and_more'),
    ]

    operations = [
        # Удаляем все Schedule перед добавлением обязательного поля
        migrations.RunPython(
            delete_all_schedules,
            reverse_delete_all_schedules,
        ),
        
        # Добавляем ManyToManyField locations в Employee
        migrations.AddField(
            model_name='employee',
            name='locations',
            field=models.ManyToManyField(
                related_name='employees',
                to='providers.providerlocation',
                verbose_name='Locations',
                help_text='Locations where this employee works'
            ),
        ),
        
        # Добавляем ForeignKey provider_location в Schedule как nullable
        # (так как все Schedule удалены, это безопасно)
        migrations.AddField(
            model_name='schedule',
            name='provider_location',
            field=models.ForeignKey(
                null=True,  # Временно nullable, так как все Schedule удалены
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schedules',
                to='providers.providerlocation',
                verbose_name='Provider Location',
                help_text='Location where this schedule applies'
            ),
        ),
        
        # Делаем поле обязательным (так как все Schedule удалены, это безопасно)
        migrations.AlterField(
            model_name='schedule',
            name='provider_location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='schedules',
                to='providers.providerlocation',
                verbose_name='Provider Location',
                help_text='Location where this schedule applies'
            ),
        ),
        
        # Обновляем unique_together в Schedule
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('employee', 'provider_location', 'day_of_week')},
        ),
        
        # Удаляем старые индексы (если есть)
        migrations.AlterIndexTogether(
            name='schedule',
            index_together=set(),
        ),
        
        # Добавляем новые индексы
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['employee', 'provider_location'], name='providers_s_employe_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day_of_week'], name='providers_s_day_of__idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_working'], name='providers_s_is_work_idx'),
        ),
    ]
