# Generated by Django 5.2.5 on 2025-11-13 19:08

from django.db import migrations, models


def create_indexes_if_not_exists(apps, schema_editor):
    """
    Создает индексы, если они еще не существуют.
    """
    with schema_editor.connection.cursor() as cursor:
        # Проверяем и создаем индексы для Schedule
        indexes_schedule = [
            ('providers_s_employe_b475ef_idx', 'CREATE INDEX IF NOT EXISTS providers_s_employe_b475ef_idx ON providers_schedule (employee_id, provider_location_id)'),
            ('providers_s_day_of__idx', 'CREATE INDEX IF NOT EXISTS providers_s_day_of__idx ON providers_schedule (day_of_week)'),
            ('providers_s_is_work_idx', 'CREATE INDEX IF NOT EXISTS providers_s_is_work_idx ON providers_schedule (is_working)'),
        ]
        
        for index_name, create_sql in indexes_schedule:
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            """, [index_name])
            if not cursor.fetchone():
                cursor.execute(create_sql)
        
        # Проверяем и создаем индексы для SchedulePattern
        indexes_pattern = [
            ('providers_s_provide_665e3a_idx', 'CREATE INDEX IF NOT EXISTS providers_s_provide_665e3a_idx ON providers_schedulepattern (provider_location_id, name)'),
            ('providers_s_name_idx', 'CREATE INDEX IF NOT EXISTS providers_s_name_idx ON providers_schedulepattern (name)'),
        ]
        
        for index_name, create_sql in indexes_pattern:
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            """, [index_name])
            if not cursor.fetchone():
                cursor.execute(create_sql)


def reverse_create_indexes(apps, schema_editor):
    """
    Удаляет индексы (обратная операция).
    """
    with schema_editor.connection.cursor() as cursor:
        indexes = [
            'providers_s_employe_b475ef_idx',
            'providers_s_day_of__idx',
            'providers_s_is_work_idx',
            'providers_s_provide_665e3a_idx',
            'providers_s_name_idx',
        ]
        for index_name in indexes:
            cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_alter_schedule_options_alter_schedulepattern_options_and_more'),
    ]

    operations = [
        # Создаем индексы через RunPython, чтобы проверить их существование
        migrations.RunPython(
            create_indexes_if_not_exists,
            reverse_create_indexes,
        ),
        # Синхронизируем состояние Django
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Индексы уже созданы выше
            state_operations=[
                migrations.AddIndex(
                    model_name='schedule',
                    index=models.Index(fields=['employee', 'provider_location'], name='providers_s_employe_b475ef_idx'),
                ),
                migrations.AddIndex(
                    model_name='schedule',
                    index=models.Index(fields=['day_of_week'], name='providers_s_day_of__idx'),
                ),
                migrations.AddIndex(
                    model_name='schedule',
                    index=models.Index(fields=['is_working'], name='providers_s_is_work_idx'),
                ),
                migrations.AddIndex(
                    model_name='schedulepattern',
                    index=models.Index(fields=['provider_location', 'name'], name='providers_s_provide_665e3a_idx'),
                ),
                migrations.AddIndex(
                    model_name='schedulepattern',
                    index=models.Index(fields=['name'], name='providers_s_name_idx'),
                ),
            ],
        ),
    ]
