# Generated by Django 5.2.5 on 2025-11-13 19:29

from django.db import migrations


def remove_old_indexes_if_exist(apps, schema_editor):
    """
    Удаляет старые индексы, если они существуют в базе данных.
    """
    with schema_editor.connection.cursor() as cursor:
        # Список старых индексов для удаления
        old_indexes = [
            'providers_s_employe_idx',
            'providers_s_provide_123abc_idx',
        ]
        
        for index_name in old_indexes:
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            """, [index_name])
            if cursor.fetchone():
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


def reverse_remove_old_indexes(apps, schema_editor):
    """
    Обратная операция - не восстанавливаем старые индексы.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_schedule_providers_s_employe_b475ef_idx_and_more'),
    ]

    operations = [
        # Удаляем старые индексы из базы данных, если они существуют
        migrations.RunPython(
            remove_old_indexes_if_exist,
            reverse_remove_old_indexes,
        ),
        # Синхронизируем состояние Django - удаляем индексы из состояния
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Индексы уже удалены выше
            state_operations=[
                migrations.RemoveIndex(
                    model_name='schedule',
                    name='providers_s_employe_idx',
                ),
                migrations.RemoveIndex(
                    model_name='schedulepattern',
                    name='providers_s_provide_123abc_idx',
                ),
            ],
        ),
    ]
