# Generated by Django 5.2.5 on 2025-11-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_remove_schedule_providers_s_employe_idx_and_more'),
    ]

    operations = [
        # Синхронизируем состояние Django - удаляем дубликаты индексов из состояния
        # Индексы остаются в базе данных, так как они определены в модели
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Не удаляем индексы из БД, они должны остаться
            state_operations=[
                migrations.RemoveIndex(
                    model_name='schedule',
                    name='providers_s_day_of__idx',
                ),
                migrations.RemoveIndex(
                    model_name='schedule',
                    name='providers_s_is_work_idx',
                ),
                migrations.RemoveIndex(
                    model_name='schedulepattern',
                    name='providers_s_name_idx',
                ),
            ],
        ),
    ]
