# Generated by Django 5.2.5 on 2025-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('geolocation', '0005_address_latitude_address_longitude'),
        ('providers', '0015_remove_schedule_providers_s_day_of__idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='activation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('activation_required', 'Activation Required'), ('active', 'Active'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', help_text='Status of provider activation process', max_length=20, verbose_name='Activation Status'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether the organization is currently active. Automatically set to True when activation_status is "active".', verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['activation_status'], name='providers_p_activat_413589_idx'),
        ),
    ]
