# Generated by Django 5.2.5 on 2025-11-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_add_activation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day Of Week')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether the location is closed on this day', verbose_name='Is Closed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider_location', models.ForeignKey(help_text='Location this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location_schedules', to='providers.providerlocation', verbose_name='Provider Location')),
            ],
            options={
                'verbose_name': 'Location Schedule',
                'verbose_name_plural': 'Location Schedules',
            },
        ),
        migrations.DeleteModel(
            name='ProviderSchedule',
        ),
        migrations.AddIndex(
            model_name='locationschedule',
            index=models.Index(fields=['weekday'], name='providers_l_weekday_825d42_idx'),
        ),
        migrations.AddIndex(
            model_name='locationschedule',
            index=models.Index(fields=['is_closed'], name='providers_l_is_clos_95ddfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationschedule',
            unique_together={('provider_location', 'weekday')},
        ),
    ]
