# Generated by Django 5.2.5 on 2026-01-01 17:18

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_public_offer_models'),
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('geolocation', '0005_address_latitude_address_longitude'),
        ('providers', '0017_locationschedule_delete_providerschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for invoices', max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country of registration. Main trigger for regional addendums and VAT requirements.', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='provider',
            name='director_name',
            field=models.CharField(blank=True, help_text='Full name of director (for offer template substitution)', max_length=200, verbose_name='Director Name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN - required for EU/UA. For Russia, use "Account Number" field instead', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='provider',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, help_text='Currency for provider invoices', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='billing.currency', verbose_name='Invoice Currency'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_eu',
            field=models.BooleanField(db_index=True, default=False, help_text='Automatically set based on country. True if country is in EU. Used for filtering and VAT requirements.', verbose_name='Is EU Country'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_vat_payer',
            field=models.BooleanField(default=False, help_text='Whether the organization is a VAT payer', verbose_name='Is VAT Payer'),
        ),
        migrations.AddField(
            model_name='provider',
            name='kpp',
            field=models.CharField(blank=True, help_text='KPP (КПП) - required for Russian LLCs, hidden for other countries', max_length=20, verbose_name='KPP (Russia only)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Type of organization: ИП, ООО, Corp, LLC, etc.', max_length=50, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='provider',
            name='show_services',
            field=models.BooleanField(default=False, help_text='Whether provider services should be displayed on UI. Provider can toggle this in admin panel.', verbose_name='Show Services'),
        ),
        migrations.AddField(
            model_name='provider',
            name='show_services_toggled_at',
            field=models.DateTimeField(blank=True, help_text='When show_services was last toggled', null=True, verbose_name='Show Services Toggled At'),
        ),
        migrations.AddField(
            model_name='provider',
            name='swift_bic',
            field=models.CharField(blank=True, help_text='SWIFT / BIC - bank identifier', max_length=11, verbose_name='SWIFT / BIC'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Number (EU VAT ID) - required for EU VAT payers. Format: PL12345678', max_length=50, verbose_name='VAT Number (EU VAT ID)'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verification_date',
            field=models.DateTimeField(blank=True, help_text='Date when VAT number was verified via VIES API', null=True, verbose_name='VAT Verification Date'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verified',
            field=models.BooleanField(default=False, help_text='Whether VAT number was verified via VIES API', verbose_name='VAT Verified'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['country', 'is_eu'], name='providers_p_country_2756e4_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_eu'], name='providers_p_is_eu_4a1df1_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['show_services', 'is_active'], name='providers_p_show_se_843171_idx'),
        ),
    ]
