# Generated by Django 5.2.10 on 2026-01-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0018_add_public_offer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='vat_verification_manual_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when VAT ID was manually confirmed', null=True, verbose_name='Manually Verified At'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verification_manual_by',
            field=models.ForeignKey(blank=True, help_text='User who manually confirmed VAT ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_verified_vat_providers', to=settings.AUTH_USER_MODEL, verbose_name='Manually Verified By'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verification_manual_comment',
            field=models.TextField(blank=True, help_text='Comment when manually confirming VAT ID (required if manually confirmed)', verbose_name='Manual Verification Comment'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verification_manual_override',
            field=models.BooleanField(default=False, help_text='Whether VAT ID was manually confirmed by administrator (checked on VIES website)', verbose_name='VAT ID Manually Confirmed'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verification_result',
            field=models.JSONField(blank=True, help_text='Result of VAT ID verification from VIES API (company name, address, etc.)', null=True, verbose_name='VAT Verification Result'),
        ),
        migrations.AddField(
            model_name='provider',
            name='vat_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('failed', 'Verification Failed')], default='pending', help_text='Status of VAT ID verification', max_length=20, verbose_name='VAT Verification Status'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='kpp',
            field=models.CharField(blank=True, help_text='KPP (tax registration reason code) - required for Russian LLCs, hidden for other countries', max_length=20, verbose_name='KPP (Russia only)'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Type of organization: SP, OOO, Corp, LLC, etc.', max_length=50, verbose_name='Organization Type'),
        ),
    ]
