# Generated by Django 5.2.10 on 2026-01-30 14:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_add_side_letter_fields'),
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('geolocation', '0006_add_is_valid_to_address'),
        ('providers', '0019_add_vat_verification_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Registration number (unique per country, required for approval). Format: letters, digits, spaces, hyphens. Minimum 3 characters.', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Registration number can only contain letters, digits, spaces, and hyphens.', regex='^[a-zA-Zа-яА-ЯёЁ0-9\\s-]+$'), django.core.validators.MinLengthValidator(3, message='Registration number must be at least 3 characters long.')], verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number / INN (unique per country, required for approval). Format: letters, digits, spaces, hyphens. Minimum 3 characters.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Tax ID can only contain letters, digits, spaces, and hyphens.', regex='^[a-zA-Zа-яА-ЯёЁ0-9\\s-]+$'), django.core.validators.MinLengthValidator(3, message='Tax ID must be at least 3 characters long.')], verbose_name='Tax ID / INN'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT Number (EU VAT ID) - required for EU VAT payers. Unique per country. Format: PL12345678', max_length=50, verbose_name='VAT Number (EU VAT ID)'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('country__isnull', False), models.Q(('country', ''), _negated=True), ('tax_id__gt', '')), fields=('country', 'tax_id'), name='providers_provider_unique_tax_id_per_country'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('country__isnull', False), models.Q(('country', ''), _negated=True), ('registration_number__gt', '')), fields=('country', 'registration_number'), name='providers_provider_unique_reg_num_per_country'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('country__isnull', False), models.Q(('country', ''), _negated=True), ('vat_number__gt', '')), fields=('country', 'vat_number'), name='providers_provider_unique_vat_per_country'),
        ),
    ]
