# Generated by Django 5.2.10 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0020_unique_per_country_tax_reg_vat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(
                condition=models.Q(('iban__gt', '')),
                fields=('iban',),
                name='providers_provider_unique_iban',
            ),
        ),
    ]
