# Generated by Django 5.2.10 on 2026-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0021_provider_unique_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN - required for EU/UA. Unique per system (one account per legal entity). For Russia, use "Account Number" field instead', max_length=34, verbose_name='IBAN'),
        ),
    ]
