# Generated by Django 5.2.10 on 2026-02-09 12:09

import django.db.models.deletion
from django.db import migrations, models


def fill_null_structured_address(apps, schema_editor):
    """Для существующих локаций с пустым адресом создаём placeholder и привязываем его."""
    ProviderLocation = apps.get_model('providers', 'ProviderLocation')
    Address = apps.get_model('geolocation', 'Address')
    null_locations = ProviderLocation.objects.filter(structured_address_id__isnull=True)
    if not null_locations.exists():
        return
    placeholder = Address.objects.create(
        formatted_address='(Address to be set - migration placeholder)',
    )
    null_locations.update(structured_address_id=placeholder.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0006_add_is_valid_to_address'),
        ('providers', '0022_alter_provider_iban'),
    ]

    operations = [
        migrations.RunPython(fill_null_structured_address, noop_reverse),
        migrations.AlterField(
            model_name='providerlocation',
            name='structured_address',
            field=models.ForeignKey(help_text='Structured address with validation and coordinates (required for service location)', on_delete=django.db.models.deletion.PROTECT, related_name='provider_locations', to='geolocation.address', verbose_name='Structured Address'),
        ),
    ]
