# Generated by Django 5.2.10 on 2026-02-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0023_require_provider_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('provider_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_shifts', to='providers.providerlocation', verbose_name='Provider Location')),
            ],
            options={
                'verbose_name': 'Holiday shift',
                'verbose_name_plural': 'Holiday shifts',
                'ordering': ['date', 'provider_location'],
                'constraints': [models.UniqueConstraint(fields=('provider_location', 'date'), name='providers_holidayshift_location_date_uniq')],
            },
        ),
    ]
