# Generated by Django 5.2.10 on 2026-02-10 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0024_holidayshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlocation',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User who accepted the manager invite for this location (for support/escalation only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_provider_locations', to=settings.AUTH_USER_MODEL, verbose_name='Location manager'),
        ),
        migrations.CreateModel(
            name='LocationManagerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the user to invite (must exist in the system)', max_length=254, verbose_name='Email')),
                ('token', models.CharField(help_text='6-digit activation code', max_length=6, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('provider_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_invites', to='providers.providerlocation', verbose_name='Provider location')),
            ],
            options={
                'verbose_name': 'Location manager invite',
                'verbose_name_plural': 'Location manager invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='providers_l_token_c19604_idx'), models.Index(fields=['expires_at'], name='providers_l_expires_5f27f7_idx')],
            },
        ),
    ]
