# Generated by Django 5.2.10 on 2026-02-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_service_description_de_service_description_me_and_more'),
        ('pets', '0007_weight_driven_pricing_sizerule_pet'),
        ('providers', '0025_add_provider_location_manager_and_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Fallback price when no size variant matches', max_digits=10, verbose_name='Base Price')),
                ('base_duration_minutes', models.PositiveIntegerField(default=30, help_text='Fallback duration in minutes when no size variant matches', verbose_name='Base Duration (minutes)')),
                ('location', models.ForeignKey(help_text='Location offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='providers.providerlocation', verbose_name='Location')),
                ('pet_type', models.ForeignKey(help_text='Pet type (dog, cat, etc.) for this price row', on_delete=django.db.models.deletion.CASCADE, related_name='location_service_prices', to='pets.pettype', verbose_name='Pet Type')),
                ('service', models.ForeignKey(help_text='Service at this location', on_delete=django.db.models.deletion.CASCADE, related_name='location_service_prices', to='catalog.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Location Service Price',
                'verbose_name_plural': 'Location Service Prices',
                'ordering': ['location', 'service', 'pet_type'],
                'unique_together': {('location', 'service', 'pet_type')},
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(help_text='Size category: S, M, L, XL (must match SizeRule)', max_length=10, verbose_name='Size Code')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this size', max_digits=10, verbose_name='Price')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Service duration in minutes for this size', verbose_name='Duration (minutes)')),
                ('service_price', models.ForeignKey(help_text='Parent price row (location + service + pet type)', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='providers.locationserviceprice', verbose_name='Location Service Price')),
            ],
            options={
                'verbose_name': 'Service Variant',
                'verbose_name_plural': 'Service Variants',
                'ordering': ['service_price', 'size_code'],
                'unique_together': {('service_price', 'size_code')},
            },
        ),
    ]
