# Generated by Django 5.2.10 on 2026-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_weight_driven_pricing_sizerule_pet'),
        ('providers', '0026_weight_driven_pricing_location_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlocation',
            name='served_pet_types',
            field=models.ManyToManyField(blank=True, help_text='Pet types (e.g. dog, cat) that this location serves. Required before adding services and prices.', related_name='provider_locations_served', to='pets.pettype', verbose_name='Served pet types'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='size_code',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], help_text='Size category: S, M, L, XL (must match SizeRule)', max_length=10, verbose_name='Size Code'),
        ),
    ]
