# Generated by Django 5.2.10 on 2026-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0028_simplify_location_service_price_single_table'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='providers_e_positio_895454_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
