# Generated by Django 5.2.10 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0029_remove_employee_position_bio_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerlocationservice',
            options={
                'ordering': ['location', 'service', 'pet_type', 'size_code'],
                'verbose_name': 'Provider Location Service',
                'verbose_name_plural': 'Provider Location Services',
            },
        ),
        migrations.AlterField(
            model_name='providerlocationservice',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Price of the service at this location for this pet type and size',
                max_digits=10,
                verbose_name='Price',
            ),
        ),
    ]
