# Generated by Django 5.2.10 on 2026-02-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_service_is_client_facing'),
        ('providers', '0033_employeelocationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLocationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('location_manager', 'Location manager'), ('service_worker', 'Service worker'), ('technical_worker', 'Technical worker')], help_text='Staff role at this location. Only one location_manager per location.', max_length=20, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Employee location role',
                'verbose_name_plural': 'Employee location roles',
            },
        ),
        migrations.RenameIndex(
            model_name='locationstaffinvite',
            new_name='providers_l_token_d6cb27_idx',
            old_name='providers_l_token_8a2b12_idx',
        ),
        migrations.RenameIndex(
            model_name='locationstaffinvite',
            new_name='providers_l_expires_186add_idx',
            old_name='providers_l_expires_3c4d56_idx',
        ),
        migrations.RenameIndex(
            model_name='locationstaffinvite',
            new_name='providers_l_provide_4559b0_idx',
            old_name='providers_l_provide_9e8f01_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(help_text='Services this employee can provide', to='catalog.service', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='employeelocationrole',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_roles', to='providers.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeelocationrole',
            name='provider_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='providers.providerlocation', verbose_name='Location'),
        ),
        migrations.AddIndex(
            model_name='employeelocationrole',
            index=models.Index(fields=['provider_location', 'role'], name='prov_emplocrole_loc_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeelocationrole',
            constraint=models.UniqueConstraint(fields=('employee', 'provider_location'), name='providers_employeelocationrole_employee_location_uniq'),
        ),
        migrations.AddConstraint(
            model_name='employeelocationrole',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'location_manager')), fields=('provider_location',), name='providers_employeelocationrole_one_manager_per_location'),
        ),
    ]
