# Generated by Django 5.2.10 on 2026-02-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0035_remove_employee_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOwnerManagerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the user to invite (must exist in the system)', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('provider_manager', 'Manager')], help_text='Owner or manager of the organization', max_length=20, verbose_name='Role')),
                ('token', models.CharField(help_text='6-digit activation code', max_length=6, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_manager_invites', to='providers.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Provider owner/manager invite',
                'verbose_name_plural': 'Provider owner/manager invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='providers_p_token_3ed807_idx'), models.Index(fields=['expires_at'], name='providers_p_expires_8995ca_idx'), models.Index(fields=['provider', 'role'], name='providers_p_provide_85ca66_idx')],
            },
        ),
    ]
