# Generated by Django 5.2.10 on 2026-02-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0037_remove_managertransferinvite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeprovider',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeprovider',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('provider_manager', 'Provider manager'), ('provider_admin', 'Provider admin'), ('service_worker', 'Service worker'), ('technical_worker', 'Technical worker')], default='service_worker', help_text='Role at this provider: owner, manager, admin, service worker, technical worker', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprovider',
            unique_together={('employee', 'provider', 'role', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='employeeprovider',
            index=models.Index(fields=['provider', 'role'], name='providers_e_provide_899f7a_idx'),
        ),
    ]
