# Generated by Django 5.2.10 on 2026-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0042_remove_employeejoinrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeeprovider',
            new_name='providers_e_provide_964b6d_idx',
            old_name='providers_e_provide_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeprovider',
            new_name='providers_e_provide_1bc70b_idx',
            old_name='providers_e_provide_mgr_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeprovider',
            new_name='providers_e_provide_adecc2_idx',
            old_name='providers_e_provide_adm_idx',
        ),
        migrations.AlterField(
            model_name='employeeprovider',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Whether this employee is a manager at this provider (aligns with is_provider_manager)', verbose_name='Is Manager'),
        ),
        migrations.AlterField(
            model_name='providerownermanagerinvite',
            name='role',
            field=models.CharField(choices=[('provider_manager', 'Manager')], help_text='Manager of the organization (owner is set at registration only)', max_length=20, verbose_name='Role'),
        ),
    ]
