# Generated by Django 5.2.10 on 2026-02-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0043_rename_providers_e_provide_owner_idx_providers_e_provide_964b6d_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='LocationManagerInvite'),
        migrations.DeleteModel(name='LocationStaffInvite'),
        migrations.DeleteModel(name='ProviderOwnerManagerInvite'),
    ]
