# Generated by Django 5.2.10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_legacy_invite_models'),
        ('providers', '0044_remove_legacy_invite_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_form',
            field=models.ForeignKey(
                blank=True,
                help_text='Application form that created this provider; used to assign staff roles on activation.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_provider',
                to='users.providerform',
                verbose_name='Provider form',
            ),
        ),
    ]
