# Generated by Django 5.2.11 on 2026-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0045_provider_provider_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the working day', null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of the working day', null=True, verbose_name='Start Time'),
        ),
    ]
