# Generated by Django 5.2.11 on 2026-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0046_schedule_nullable_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocationrole',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when employee was deactivated at this location.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='employeelocationrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the employee is currently active at this location. Set to False for soft-delete / deactivation (offboarding).', verbose_name='Is Active'),
        ),
    ]
