# Generated by Django 5.2.11 on 2026-03-19 16:02

import django.db.models.deletion
import providers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0047_employeelocationrole_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderReportExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=64, verbose_name='Report Code')),
                ('scope', models.CharField(max_length=20, verbose_name='Scope')),
                ('export_format', models.CharField(choices=[('xlsx', 'XLSX')], default='xlsx', max_length=20, verbose_name='Export Format')),
                ('language_code', models.CharField(default='en', max_length=16, verbose_name='Language Code')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to=providers.models.provider_report_export_upload_to, verbose_name='File')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Filename')),
                ('task_id', models.CharField(blank=True, max_length=128, verbose_name='Task Id')),
                ('export_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Export Token')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_export_jobs', to='providers.providerlocation', verbose_name='Location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_jobs', to='providers.provider', verbose_name='Provider')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_report_export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Provider Report Export Job',
                'verbose_name_plural': 'Provider Report Export Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='providers_p_provide_475c79_idx'), models.Index(fields=['requested_by', 'status'], name='providers_p_request_05d8f8_idx'), models.Index(fields=['created_at'], name='providers_p_created_5c2074_idx')],
            },
        ),
    ]
