# Generated by Django 5.2.11 on 2026-03-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0048_providerreportexportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerreportexportjob',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Downloaded At'),
        ),
    ]
