# Generated by Django 5.2.11 on 2026-03-30 13:33

import django.db.models.deletion
from django.db import migrations, models, transaction
from django.db.models import Q
from django.utils import timezone


ACCESS_ROLE_DEFINITIONS = {
    'owner': {
        'name_en': 'Owner',
        'name_ru': 'Владелец',
        'name_me': 'Vlasnik',
        'name_de': 'Eigentümer',
        'description': 'Provider owner access role.',
        'permissions': [],
        'is_active': True,
    },
    'provider_admin': {
        'name_en': 'Provider admin',
        'name_ru': 'Администратор учреждения',
        'name_me': 'Administrator ustanove',
        'name_de': 'Einrichtungsadministrator',
        'description': 'Provider organization admin access role.',
        'permissions': [],
        'is_active': True,
    },
    'provider_manager': {
        'name_en': 'Provider manager',
        'name_ru': 'Менеджер учреждения',
        'name_me': 'Menadžer ustanove',
        'name_de': 'Einrichtungsmanager',
        'description': 'Provider organization manager access role.',
        'permissions': [],
        'is_active': True,
    },
    'branch_manager': {
        'name_en': 'Branch manager',
        'name_ru': 'Менеджер филиала',
        'name_me': 'Menadžer filijale',
        'name_de': 'Filialleiter',
        'description': 'Branch manager access role.',
        'permissions': [],
        'is_active': True,
    },
    'specialist': {
        'name_en': 'Specialist',
        'name_ru': 'Специалист',
        'name_me': 'Specijalista',
        'name_de': 'Spezialist',
        'description': 'Legacy provider worker access role.',
        'permissions': [],
        'is_active': True,
    },
    'worker': {
        'name_en': 'Worker',
        'name_ru': 'Сотрудник',
        'name_me': 'Radnik',
        'name_de': 'Mitarbeiter',
        'description': 'Provider worker access alias for the new RBAC model.',
        'permissions': [],
        'is_active': True,
    },
}
FORWARD_PROVIDER_ROLE_MAP = {
    'service_worker': 'worker',
    'technical_worker': 'worker',
}
FORWARD_LOCATION_ROLE_MAP = {
    'location_manager': 'branch_manager',
    'service_worker': 'worker',
    'technical_worker': 'worker',
}
REVERSE_PROVIDER_ROLE_MAP = {
    'worker': 'service_worker',
}
REVERSE_LOCATION_ROLE_MAP = {
    'branch_manager': 'location_manager',
    'worker': 'service_worker',
}
PROVIDER_ACCESS_ROLE_NAMES = tuple(ACCESS_ROLE_DEFINITIONS.keys())


def _get_location_through_field_names(Employee, ProviderLocation):
    through_model = Employee._meta.get_field('locations').remote_field.through
    employee_field_name = None
    location_field_name = None
    for field in through_model._meta.fields:
        remote_model = getattr(getattr(field, 'remote_field', None), 'model', None)
        if remote_model is Employee:
            employee_field_name = field.name
        elif remote_model is ProviderLocation:
            location_field_name = field.name
    return through_model, employee_field_name, location_field_name


def _ensure_employee_location_membership(db_alias, Employee, ProviderLocation, employee_id, provider_location_id):
    through_model, employee_field_name, location_field_name = _get_location_through_field_names(Employee, ProviderLocation)
    if not employee_field_name or not location_field_name:
        return
    through_model.objects.using(db_alias).get_or_create(
        **{
            f'{employee_field_name}_id': employee_id,
            f'{location_field_name}_id': provider_location_id,
        }
    )


def _canonical_provider_role(record):
    if getattr(record, 'is_owner', False):
        return 'owner'
    if getattr(record, 'is_provider_admin', False):
        return 'provider_admin'
    if getattr(record, 'is_provider_manager', False):
        return 'provider_manager'
    role = getattr(record, 'role', '') or 'worker'
    return FORWARD_PROVIDER_ROLE_MAP.get(role, role if role in {'owner', 'provider_admin', 'provider_manager', 'worker'} else 'worker')


def _canonical_location_role(role_value):
    return FORWARD_LOCATION_ROLE_MAP.get(role_value, role_value if role_value in {'branch_manager', 'worker'} else 'worker')


def _iter_active_location_manager_roles(EmployeeLocationRole, db_alias, role_code):
    now = timezone.now()
    return EmployeeLocationRole.objects.using(db_alias).filter(
        role=role_code,
        is_active=True,
    ).filter(
        Q(end_date__isnull=True) | Q(end_date__gte=now)
    )


def _sync_access_roles(apps, schema_editor, *, include_worker_alias):
    db_alias = schema_editor.connection.alias
    User = apps.get_model('users', 'User')
    UserType = apps.get_model('users', 'UserType')
    EmployeeProvider = apps.get_model('providers', 'EmployeeProvider')
    EmployeeLocationRole = apps.get_model('providers', 'EmployeeLocationRole')
    ProviderLocation = apps.get_model('providers', 'ProviderLocation')

    today = timezone.localdate()
    now = timezone.now()
    role_names = PROVIDER_ACCESS_ROLE_NAMES if include_worker_alias else tuple(
        role_name for role_name in PROVIDER_ACCESS_ROLE_NAMES if role_name != 'worker'
    )
    role_objects = {}
    for role_name in role_names:
        role_object, _ = UserType.objects.using(db_alias).get_or_create(
            name=role_name,
            defaults=dict(ACCESS_ROLE_DEFINITIONS[role_name]),
        )
        role_objects[role_name] = role_object

    relevant_user_ids = set(
        User.objects.using(db_alias).filter(user_types__name__in=PROVIDER_ACCESS_ROLE_NAMES).values_list('id', flat=True)
    )
    relevant_user_ids.update(
        EmployeeProvider.objects.using(db_alias).exclude(employee__user_id__isnull=True).values_list('employee__user_id', flat=True)
    )
    relevant_user_ids.update(
        EmployeeLocationRole.objects.using(db_alias).exclude(employee__user_id__isnull=True).values_list('employee__user_id', flat=True)
    )
    relevant_user_ids.update(
        ProviderLocation.objects.using(db_alias).exclude(manager_id__isnull=True).values_list('manager_id', flat=True)
    )

    worker_role_values = ('worker',) if include_worker_alias else ('service_worker', 'technical_worker')
    manager_role_values = ('branch_manager',) if include_worker_alias else ('location_manager',)

    for user_id in relevant_user_ids:
        active_provider_links = EmployeeProvider.objects.using(db_alias).filter(
            employee__user_id=user_id,
            employee__is_active=True,
        ).filter(
            Q(end_date__isnull=True) | Q(end_date__gte=today)
        )
        active_location_roles = EmployeeLocationRole.objects.using(db_alias).filter(
            employee__user_id=user_id,
            employee__is_active=True,
            is_active=True,
            provider_location__is_active=True,
        ).filter(
            Q(end_date__isnull=True) | Q(end_date__gte=now)
        )

        target_roles = set()
        if active_provider_links.filter(is_owner=True).exists():
            target_roles.add('owner')
        if active_provider_links.filter(is_provider_admin=True).exists():
            target_roles.add('provider_admin')
        if active_provider_links.filter(is_provider_manager=True).exists():
            target_roles.add('provider_manager')
        if active_location_roles.filter(role__in=manager_role_values).exists() or ProviderLocation.objects.using(db_alias).filter(
            manager_id=user_id,
            is_active=True,
        ).exists():
            target_roles.add('branch_manager')
        if active_location_roles.exists() or active_provider_links.filter(role__in=worker_role_values).exists():
            target_roles.add('specialist')
            if include_worker_alias:
                target_roles.add('worker')

        user = User.objects.using(db_alias).get(pk=user_id)
        existing_roles = set(user.user_types.filter(name__in=PROVIDER_ACCESS_ROLE_NAMES).values_list('name', flat=True))

        for role_name in target_roles - existing_roles:
            user.user_types.add(role_objects[role_name])

        roles_to_remove = existing_roles - target_roles
        if roles_to_remove:
            removable_roles = list(UserType.objects.using(db_alias).filter(name__in=roles_to_remove))
            if removable_roles:
                user.user_types.remove(*removable_roles)

    if not include_worker_alias:
        UserType.objects.using(db_alias).filter(name='worker').delete()


def seed_provider_rbac(apps, schema_editor):
    with transaction.atomic():
        _seed_provider_rbac(apps, schema_editor)


def unseed_provider_rbac(apps, schema_editor):
    with transaction.atomic():
        _unseed_provider_rbac(apps, schema_editor)


def _seed_provider_rbac(apps, schema_editor):
    from providers.rbac_defaults import PERMISSION_MATRIX, RESOURCE_DEFINITIONS, ROLE_DEFINITIONS

    db_alias = schema_editor.connection.alias
    ProviderRole = apps.get_model('providers', 'ProviderRole')
    ProviderResource = apps.get_model('providers', 'ProviderResource')
    ProviderRolePermission = apps.get_model('providers', 'ProviderRolePermission')
    EmployeeProvider = apps.get_model('providers', 'EmployeeProvider')
    EmployeeLocationRole = apps.get_model('providers', 'EmployeeLocationRole')
    ProviderLocation = apps.get_model('providers', 'ProviderLocation')
    Employee = apps.get_model('providers', 'Employee')

    role_map = {}
    for role_data in ROLE_DEFINITIONS:
        role_object, _ = ProviderRole.objects.using(db_alias).update_or_create(
            code=role_data['code'],
            defaults={
                'name': role_data['name'],
                'description': role_data['description'],
                'level': role_data['level'],
                'is_active': True,
            },
        )
        role_map[role_data['code']] = role_object

    resource_map = {}
    for resource_data in RESOURCE_DEFINITIONS:
        resource_object, _ = ProviderResource.objects.using(db_alias).update_or_create(
            code=resource_data['code'],
            defaults={
                'name': resource_data['name'],
                'description': resource_data['description'],
                'sort_order': resource_data['sort_order'],
                'is_active': True,
                'parent': None,
            },
        )
        resource_map[resource_data['code']] = resource_object

    for resource_data in RESOURCE_DEFINITIONS:
        parent_code = resource_data['parent_code']
        ProviderResource.objects.using(db_alias).filter(pk=resource_map[resource_data['code']].pk).update(
            parent_id=resource_map[parent_code].pk if parent_code else None,
        )

    for role_code, resources in PERMISSION_MATRIX.items():
        for resource_code, permission_data in resources.items():
            ProviderRolePermission.objects.using(db_alias).update_or_create(
                role_id=role_map[role_code].pk,
                resource_id=resource_map[resource_code].pk,
                defaults=permission_data,
            )

    for employee_provider in EmployeeProvider.objects.using(db_alias).all().iterator():
        updates = {}
        target_role = _canonical_provider_role(employee_provider)
        if employee_provider.role != target_role:
            updates['role'] = target_role
        target_is_manager = bool(employee_provider.is_provider_manager)
        if bool(employee_provider.is_manager) != target_is_manager:
            updates['is_manager'] = target_is_manager
        if updates:
            EmployeeProvider.objects.using(db_alias).filter(pk=employee_provider.pk).update(**updates)

    for location_role in EmployeeLocationRole.objects.using(db_alias).all().iterator():
        target_role = _canonical_location_role(location_role.role)
        if location_role.role != target_role:
            EmployeeLocationRole.objects.using(db_alias).filter(pk=location_role.pk).update(role=target_role)
        _ensure_employee_location_membership(
            db_alias,
            Employee,
            ProviderLocation,
            location_role.employee_id,
            location_role.provider_location_id,
        )

    now = timezone.now()
    for location in ProviderLocation.objects.using(db_alias).exclude(manager_id__isnull=True).iterator():
        has_active_branch_manager = EmployeeLocationRole.objects.using(db_alias).filter(
            provider_location_id=location.pk,
            role='branch_manager',
            is_active=True,
        ).filter(
            Q(end_date__isnull=True) | Q(end_date__gte=now)
        ).exists()
        if has_active_branch_manager:
            continue

        employee = Employee.objects.using(db_alias).filter(user_id=location.manager_id).first()
        if employee is None:
            continue

        role_row = EmployeeLocationRole.objects.using(db_alias).filter(
            employee_id=employee.pk,
            provider_location_id=location.pk,
        ).first()
        if role_row is None:
            EmployeeLocationRole.objects.using(db_alias).create(
                employee_id=employee.pk,
                provider_location_id=location.pk,
                role='branch_manager',
                is_active=True,
                end_date=None,
            )
        else:
            EmployeeLocationRole.objects.using(db_alias).filter(pk=role_row.pk).update(
                role='branch_manager',
                is_active=True,
                end_date=None,
            )
        _ensure_employee_location_membership(db_alias, Employee, ProviderLocation, employee.pk, location.pk)

    active_manager_by_location = {}
    for active_manager_role in _iter_active_location_manager_roles(EmployeeLocationRole, db_alias, 'branch_manager').order_by(
        'provider_location_id',
        '-pk',
    ).select_related('employee'):
        active_manager_by_location.setdefault(active_manager_role.provider_location_id, active_manager_role.employee.user_id)

    for location_id, manager_user_id in active_manager_by_location.items():
        ProviderLocation.objects.using(db_alias).filter(pk=location_id).update(manager_id=manager_user_id)

    _sync_access_roles(apps, schema_editor, include_worker_alias=True)


def _unseed_provider_rbac(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    EmployeeProvider = apps.get_model('providers', 'EmployeeProvider')
    EmployeeLocationRole = apps.get_model('providers', 'EmployeeLocationRole')
    ProviderLocation = apps.get_model('providers', 'ProviderLocation')

    for employee_provider in EmployeeProvider.objects.using(db_alias).filter(role__in=REVERSE_PROVIDER_ROLE_MAP.keys()).iterator():
        EmployeeProvider.objects.using(db_alias).filter(pk=employee_provider.pk).update(
            role=REVERSE_PROVIDER_ROLE_MAP.get(employee_provider.role, employee_provider.role),
        )

    for location_role in EmployeeLocationRole.objects.using(db_alias).filter(role__in=REVERSE_LOCATION_ROLE_MAP.keys()).iterator():
        EmployeeLocationRole.objects.using(db_alias).filter(pk=location_role.pk).update(
            role=REVERSE_LOCATION_ROLE_MAP.get(location_role.role, location_role.role),
        )

    active_manager_by_location = {}
    for active_manager_role in _iter_active_location_manager_roles(EmployeeLocationRole, db_alias, 'location_manager').order_by(
        'provider_location_id',
        '-pk',
    ).select_related('employee'):
        active_manager_by_location.setdefault(active_manager_role.provider_location_id, active_manager_role.employee.user_id)

    for location_id, manager_user_id in active_manager_by_location.items():
        ProviderLocation.objects.using(db_alias).filter(pk=location_id).update(manager_id=manager_user_id)

    _sync_access_roles(apps, schema_editor, include_worker_alias=False)


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0049_providerreportexportjob_downloaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Provider Resource',
                'verbose_name_plural': 'Provider Resources',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('level', models.PositiveSmallIntegerField(help_text='Hierarchy level: 1=Owner, 2=Admin, 3=Manager, 4=Branch Manager, 5=Worker', verbose_name='Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Provider Role',
                'verbose_name_plural': 'Provider Roles',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False, verbose_name='Can Create')),
                ('can_read', models.BooleanField(default=False, verbose_name='Can Read')),
                ('can_update', models.BooleanField(default=False, verbose_name='Can Update')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can Delete')),
                ('scope', models.CharField(choices=[('all', 'Full access'), ('own_branch', 'Own branches only'), ('own_only', 'Own records only')], default='all', help_text='Scope of the permission: all data, own branches only, or own records only', max_length=20, verbose_name='Scope')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Provider Role Permission',
                'verbose_name_plural': 'Provider Role Permissions',
                'ordering': ['role__level', 'resource__sort_order', 'resource__code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='employeelocationrole',
            name='providers_employeelocationrole_one_manager_per_location',
        ),
        migrations.AlterField(
            model_name='employeelocationrole',
            name='role',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('worker', 'Worker')], help_text='Staff role at this location. Only one branch manager per location.', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='employeeprovider',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('provider_manager', 'Provider manager'), ('provider_admin', 'Provider admin'), ('worker', 'Worker')], default='worker', help_text='Primary role at this provider. Effective permissions are calculated from flags and location roles.', max_length=20, verbose_name='Role'),
        ),
        migrations.AddConstraint(
            model_name='employeelocationrole',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'branch_manager')), fields=('provider_location',), name='providers_employeelocationrole_one_branch_manager_per_location'),
        ),
        migrations.AddField(
            model_name='providerresource',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent resource for hierarchical grouping (e.g., org -> org.profile)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='providers.providerresource', verbose_name='Parent Resource'),
        ),
        migrations.AddField(
            model_name='providerrolepermission',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='providers.providerresource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='providerrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='providers.providerrole', verbose_name='Role'),
        ),
        migrations.AddConstraint(
            model_name='providerrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'resource'), name='providers_rolepermission_role_resource_uniq'),
        ),
        migrations.RunPython(seed_provider_rbac, unseed_provider_rbac),
    ]
