# Generated by Django 5.2.11 on 2026-03-31 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0050_provider_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLifecycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, help_text='Technical key for the singleton settings record.', unique=True, verbose_name='Singleton Key')),
                ('owner_post_termination_access_days', models.PositiveIntegerField(default=30, help_text='How many days the owner keeps read-only access after organization termination.', verbose_name='Owner Post-Termination Access Days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Provider Lifecycle Settings',
                'verbose_name_plural': 'Provider Lifecycle Settings',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='partnership_effective_date',
            field=models.DateField(blank=True, help_text='Date when the current partnership status became effective.', null=True, verbose_name='Partnership Effective Date'),
        ),
        migrations.AddField(
            model_name='provider',
            name='partnership_reason',
            field=models.TextField(blank=True, help_text='Reason for the current partnership status.', verbose_name='Partnership Reason'),
        ),
        migrations.AddField(
            model_name='provider',
            name='partnership_resume_date',
            field=models.DateField(blank=True, help_text='Planned date when the organization is expected to return to active status.', null=True, verbose_name='Partnership Resume Date'),
        ),
        migrations.AddField(
            model_name='provider',
            name='partnership_status',
            field=models.CharField(choices=[('active', 'Active'), ('temporarily_inactive', 'Temporarily Inactive'), ('terminated', 'Terminated')], db_index=True, default='active', help_text='Operational partnership status of the organization on the platform.', max_length=30, verbose_name='Partnership Status'),
        ),
        migrations.AddField(
            model_name='provider',
            name='partnership_status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the current partnership status was last changed.', null=True, verbose_name='Partnership Status Changed At'),
        ),
        migrations.AddField(
            model_name='provider',
            name='partnership_status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who last changed the partnership status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_partnership_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Partnership Status Changed By'),
        ),
        migrations.AddField(
            model_name='provider',
            name='pending_partnership_effective_date',
            field=models.DateField(blank=True, help_text='Date when the pending partnership status should be applied.', null=True, verbose_name='Pending Partnership Effective Date'),
        ),
        migrations.AddField(
            model_name='provider',
            name='pending_partnership_reason',
            field=models.TextField(blank=True, help_text='Reason stored for the pending partnership change.', verbose_name='Pending Partnership Reason'),
        ),
        migrations.AddField(
            model_name='provider',
            name='pending_partnership_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the pending partnership change was scheduled.', null=True, verbose_name='Pending Partnership Requested At'),
        ),
        migrations.AddField(
            model_name='provider',
            name='pending_partnership_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who scheduled the pending partnership change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_pending_partnership_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pending Partnership Requested By'),
        ),
        migrations.AddField(
            model_name='provider',
            name='pending_partnership_resume_date',
            field=models.DateField(blank=True, help_text='Planned resume date stored for the pending partnership change.', null=True, verbose_name='Pending Partnership Resume Date'),
        ),
        migrations.AddField(
            model_name='provider',
            name='pending_partnership_status',
            field=models.CharField(blank=True, default='', help_text='Scheduled partnership status to apply in the future.', max_length=30, verbose_name='Pending Partnership Status'),
        ),
        migrations.AddField(
            model_name='provider',
            name='post_termination_access_until',
            field=models.DateTimeField(blank=True, help_text='Read-only owner access end time after organization termination.', null=True, verbose_name='Post-Termination Access Until'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='lifecycle_effective_date',
            field=models.DateField(blank=True, help_text='Date when the current lifecycle status became effective.', null=True, verbose_name='Lifecycle Effective Date'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='lifecycle_reason',
            field=models.TextField(blank=True, help_text='Reason for the current lifecycle status.', verbose_name='Lifecycle Reason'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='lifecycle_resume_date',
            field=models.DateField(blank=True, help_text='Planned date when the location is expected to return to active status.', null=True, verbose_name='Lifecycle Resume Date'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('temporarily_closed', 'Temporarily Closed'), ('deactivated', 'Deactivated')], db_index=True, default='active', help_text='Operational lifecycle status of the location.', max_length=30, verbose_name='Lifecycle Status'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='lifecycle_status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the current lifecycle status was last changed.', null=True, verbose_name='Lifecycle Status Changed At'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='lifecycle_status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who last changed the lifecycle status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_location_lifecycle_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Lifecycle Status Changed By'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='pending_lifecycle_effective_date',
            field=models.DateField(blank=True, help_text='Date when the pending lifecycle status should be applied.', null=True, verbose_name='Pending Lifecycle Effective Date'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='pending_lifecycle_reason',
            field=models.TextField(blank=True, help_text='Reason stored for the pending lifecycle change.', verbose_name='Pending Lifecycle Reason'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='pending_lifecycle_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the pending lifecycle change was scheduled.', null=True, verbose_name='Pending Lifecycle Requested At'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='pending_lifecycle_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who scheduled the pending lifecycle change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_location_pending_lifecycle_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pending Lifecycle Requested By'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='pending_lifecycle_resume_date',
            field=models.DateField(blank=True, help_text='Planned resume date stored for the pending lifecycle change.', null=True, verbose_name='Pending Lifecycle Resume Date'),
        ),
        migrations.AddField(
            model_name='providerlocation',
            name='pending_lifecycle_status',
            field=models.CharField(blank=True, default='', help_text='Scheduled lifecycle status to apply in the future.', max_length=30, verbose_name='Pending Lifecycle Status'),
        ),
        migrations.CreateModel(
            name='ProviderLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('provider', 'Provider'), ('location', 'Location')], help_text='Type of entity affected by the lifecycle action.', max_length=20, verbose_name='Entity Type')),
                ('action', models.CharField(choices=[('provider_pause', 'Provider Pause'), ('provider_terminate', 'Provider Terminate'), ('provider_reactivate', 'Provider Reactivate'), ('location_temporary_close', 'Location Temporary Close'), ('location_deactivate', 'Location Deactivate'), ('location_reactivate', 'Location Reactivate')], help_text='Lifecycle action that was executed or scheduled.', max_length=40, verbose_name='Action')),
                ('previous_status', models.CharField(blank=True, help_text='Previous lifecycle status before the action.', max_length=40, verbose_name='Previous Status')),
                ('new_status', models.CharField(blank=True, help_text='New lifecycle status after the action.', max_length=40, verbose_name='New Status')),
                ('effective_date', models.DateField(blank=True, help_text='Effective date of the lifecycle action.', null=True, verbose_name='Effective Date')),
                ('resume_date', models.DateField(blank=True, help_text='Planned resume date linked to the lifecycle action.', null=True, verbose_name='Resume Date')),
                ('reason', models.TextField(blank=True, help_text='Reason supplied for the lifecycle action.', verbose_name='Reason')),
                ('is_staff_override', models.BooleanField(default=False, help_text='Whether the action was initiated by platform staff override.', verbose_name='Is Staff Override')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Correlation identifier for grouped lifecycle operations.', verbose_name='Correlation ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional audit metadata for lifecycle processing.', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated the lifecycle action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('location', models.ForeignKey(blank=True, help_text='Location affected by the lifecycle action when applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='providers.providerlocation', verbose_name='Location')),
                ('provider', models.ForeignKey(help_text='Provider affected by the lifecycle action.', on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='providers.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Provider Lifecycle Event',
                'verbose_name_plural': 'Provider Lifecycle Events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'created_at'], name='providers_p_entity__f6f70c_idx'), models.Index(fields=['provider', 'created_at'], name='providers_p_provide_0bcf63_idx'), models.Index(fields=['correlation_id'], name='providers_p_correla_e670bc_idx')],
            },
        ),
    ]
