# Generated by Codex on 2026-03-31

from django.db import migrations, transaction


def seed_provider_lifecycle_rbac(apps, schema_editor):
    from providers.rbac_defaults import PERMISSION_MATRIX, RESOURCE_DEFINITIONS

    db_alias = schema_editor.connection.alias
    ProviderRole = apps.get_model('providers', 'ProviderRole')
    ProviderResource = apps.get_model('providers', 'ProviderResource')
    ProviderRolePermission = apps.get_model('providers', 'ProviderRolePermission')

    with transaction.atomic():
        resource_map = {}
        for resource_data in RESOURCE_DEFINITIONS:
            resource_object, _ = ProviderResource.objects.using(db_alias).update_or_create(
                code=resource_data['code'],
                defaults={
                    'name': resource_data['name'],
                    'description': resource_data['description'],
                    'sort_order': resource_data['sort_order'],
                    'is_active': True,
                    'parent': None,
                },
            )
            resource_map[resource_data['code']] = resource_object

        for resource_data in RESOURCE_DEFINITIONS:
            parent_code = resource_data['parent_code']
            ProviderResource.objects.using(db_alias).filter(
                pk=resource_map[resource_data['code']].pk
            ).update(
                parent_id=resource_map[parent_code].pk if parent_code else None,
            )

        for role in ProviderRole.objects.using(db_alias).filter(code__in=PERMISSION_MATRIX.keys()):
            for resource_code, permission_data in PERMISSION_MATRIX[role.code].items():
                resource = resource_map.get(resource_code)
                if resource is None:
                    continue
                ProviderRolePermission.objects.using(db_alias).update_or_create(
                    role_id=role.pk,
                    resource_id=resource.pk,
                    defaults=permission_data,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0051_providerlifecyclesettings_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_provider_lifecycle_rbac, migrations.RunPython.noop),
    ]
