# Generated by Django 5.2.11 on 2026-03-31 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_platformcompany_platformcompanycountry_and_more'),
        ('catalog', '0010_service_emergency_capability_mode_and_more'),
        ('geolocation', '0008_remove_address_is_valid_is_validated'),
        ('pets', '0025_petdocument_addendum_and_type_contract'),
        ('providers', '0052_provider_rbac_lifecycle_resource'),
        ('users', '0033_fix_project_auth_user_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], help_text='Size category: S, M, L, XL (must match SizeRule).', max_length=10, verbose_name='Size Code')),
                ('price', models.DecimalField(decimal_places=2, help_text='Organization-level price for this service, pet type, and size.', max_digits=10, verbose_name='Price')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Organization-level duration in minutes for this service row.', verbose_name='Duration In Minutes')),
                ('tech_break_minutes', models.PositiveIntegerField(default=0, help_text='Technical break time in minutes after the service.', verbose_name='Technical Break Minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this organization-level pricing row is active.', verbose_name='Is Active')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version for the organization pricing row.', verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Provider Service Pricing',
                'verbose_name_plural': 'Provider Service Pricing',
                'ordering': ['provider', 'service', 'pet_type', 'size_code'],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='use_unified_service_pricing',
            field=models.BooleanField(default=False, help_text='Whether service prices are managed centrally at the organization level and synced to branches.', verbose_name='Use Unified Service Pricing'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['use_unified_service_pricing'], name='providers_p_use_uni_87ebc4_idx'),
        ),
        migrations.AddField(
            model_name='providerservicepricing',
            name='pet_type',
            field=models.ForeignKey(help_text='Pet type covered by the organization-level price row.', on_delete=django.db.models.deletion.CASCADE, related_name='provider_pricing_rows', to='pets.pettype', verbose_name='Pet Type'),
        ),
        migrations.AddField(
            model_name='providerservicepricing',
            name='provider',
            field=models.ForeignKey(help_text='Organization that owns the unified service price row.', on_delete=django.db.models.deletion.CASCADE, related_name='service_pricing_rows', to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='providerservicepricing',
            name='service',
            field=models.ForeignKey(help_text='Service covered by the unified organization-level price.', on_delete=django.db.models.deletion.CASCADE, related_name='provider_pricing_rows', to='catalog.service', verbose_name='Service'),
        ),
        migrations.AddIndex(
            model_name='providerservicepricing',
            index=models.Index(fields=['provider', 'service'], name='prov_prc_prov_svc_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservicepricing',
            index=models.Index(fields=['is_active'], name='prov_prc_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerservicepricing',
            constraint=models.UniqueConstraint(fields=('provider', 'service', 'pet_type', 'size_code'), name='providers_providerpricing_provider_service_pet_type_size_uniq'),
        ),
    ]
