# Generated by Django 5.2.10 on 2026-02-23 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0007_weight_driven_pricing_sizerule_pet'),
        ('providers', '0043_rename_providers_e_provide_owner_idx_providers_e_provide_964b6d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_type', models.CharField(choices=[('provider_manager', 'Provider Manager'), ('provider_admin', 'Provider Admin'), ('branch_manager', 'Branch Manager'), ('specialist', 'Specialist'), ('pet_co_owner', 'Pet Co-Owner'), ('pet_transfer', 'Pet Transfer')], max_length=30, verbose_name='Invite Type')),
                ('email', models.EmailField(help_text='Email of the invited user', max_length=254, verbose_name='Email')),
                ('token', models.CharField(help_text='6-digit activation code', max_length=6, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='Declined At')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pets.pet', verbose_name='Pet')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='providers.provider', verbose_name='Provider')),
                ('provider_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='providers.providerlocation', verbose_name='Provider Location')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='invites_inv_token_e4bb9a_idx'), models.Index(fields=['email'], name='invites_inv_email_1993bd_idx'), models.Index(fields=['invite_type', 'status'], name='invites_inv_invite__68d40a_idx'), models.Index(fields=['expires_at'], name='invites_inv_expires_44c800_idx'), models.Index(fields=['provider'], name='invites_inv_provide_70c439_idx'), models.Index(fields=['provider_location'], name='invites_inv_provide_e6c0e8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('invite_type', 'specialist'), ('status', 'pending')), fields=('provider_location', 'email'), name='invites_unique_pending_specialist_per_location_email')],
            },
        ),
    ]
