# Generated by Django 5.2.5 on 2025-09-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Переименовываем таблицу с sitters_review на sitters_sitterreview
            "ALTER TABLE sitters_review RENAME TO sitters_sitterreview;",
            # Обратная миграция
            "ALTER TABLE sitters_sitterreview RENAME TO sitters_review;",
        ),
    ]
