# Generated by Codex on 2026-03-26

from django.db import migrations, models


def migrate_waiting_end_to_waiting_review(apps, schema_editor):
    """
    Обновляет legacy-статус waiting_end до waiting_review.
    """
    PetSitting = apps.get_model('sitters', 'PetSitting')
    PetSitting.objects.filter(status='waiting_end').update(status='waiting_review')


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0003_rename_review_sitterreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the sitter profile is currently visible in search', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='petsitting',
            name='status',
            field=models.CharField(
                choices=[
                    ('waiting_start', 'Waiting Start'),
                    ('active', 'Active'),
                    ('waiting_review', 'Waiting Review'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='waiting_start',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.RunPython(migrate_waiting_end_to_waiting_review, migrations.RunPython.noop),
    ]
