# Generated by Django 5.2.11 on 2026-04-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0008_remove_address_is_valid_is_validated'),
        ('pets', '0025_petdocument_addendum_and_type_contract'),
        ('sitters', '0004_sitterprofile_is_active_and_waiting_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petsittingad',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='public', help_text='Public ads are visible in search. Internal ads are created only for workflow records.', max_length=20, verbose_name='Visibility'),
        ),
        migrations.CreateModel(
            name='PetSittingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('owner_search', 'Owner Search'), ('chat', 'Chat')], default='owner_search', max_length=20, verbose_name='Source')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic version for direct pet sitting request updates.', verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitting_requests', to='sitters.conversation', verbose_name='Conversation')),
                ('created_ad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitting_request', to='sitters.petsittingad', verbose_name='Created Ad')),
                ('created_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitting_request', to='sitters.petsittingresponse', verbose_name='Created Response')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_pet_sitting_requests', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_sitting_requests_as_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_sitting_requests', to='pets.pet', verbose_name='Pet')),
                ('pet_sitting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitting_request', to='sitters.petsitting', verbose_name='Pet Sitting')),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_sitting_requests', to='sitters.sitterprofile', verbose_name='Sitter')),
                ('structured_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitting_requests', to='geolocation.address', verbose_name='Structured Address')),
            ],
            options={
                'verbose_name': 'Pet Sitting Request',
                'verbose_name_plural': 'Pet Sitting Requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('owner', 'sitter', 'pet', 'start_date', 'end_date'), name='unique_pending_pet_sitting_request')],
            },
        ),
    ]
