# Generated by Django 5.2.5 on 2025-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_service_allowed_pet_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hierarchy_order',
            field=models.CharField(blank=True, help_text='Hierarchical order for sorting (e.g., 1, 1_1, 1_2, 2_1)', max_length=100, verbose_name='Hierarchy Order'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['hierarchy_order'], name='catalog_ser_hierarc_123456_idx'),
        ),
    ]
