# Generated by Django 5.2.5 on 2025-09-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_hierarchy_order'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['hierarchy_order', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='catalog_ser_hierarc_c421f3_idx',
            old_name='catalog_ser_hierarc_123456_idx',
        ),
        migrations.AlterField(
            model_name='service',
            name='allowed_pet_types',
            field=models.ManyToManyField(blank=True, help_text='Pet types this service is available for. If empty, available for all types.', to='pets.pettype', verbose_name='Allowed Pet Types'),
        ),
    ]
