# Generated by Django 5.2.5 on 2025-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version for optimistic locking', verbose_name='Version'),
        ),
    ]
