# Generated by Django 5.2.5 on 2025-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=200, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description in English', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Description in Russian', verbose_name='Description (Russian)'),
        ),
    ]
