# Generated by Django 5.2.5 on 2025-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_service_multilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description in German', verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_me',
            field=models.TextField(blank=True, help_text='Description in Montenegrian', verbose_name='Description (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=200, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=200, verbose_name='Name (Montenegrian)'),
        ),
    ]
