# Generated by Django 5.2.11 on 2026-03-10 19:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_service_is_client_facing'),
        ('pets', '0018_add_petowner_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='search_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Synonyms and keywords for search routing', size=None, verbose_name='Search Keywords'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_keywords'], name='catalog_ser_search__a0b19c_gin'),
        ),
    ]
