# Generated by Django 5.2.11 on 2026-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_service_search_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='emergency_capability_mode',
            field=models.CharField(choices=[('inherit', 'Inherit'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='inherit', help_text='Emergency capability is modeled on hierarchy nodes and inherited by descendants by default.', max_length=16, verbose_name='Emergency Capability Mode'),
        ),
        migrations.AddField(
            model_name='service',
            name='protocol_family_mode',
            field=models.CharField(choices=[('inherit', 'Inherit'), ('none', 'None'), ('veterinary', 'Veterinary')], default='inherit', help_text='Protocol family is modeled on hierarchy nodes and inherited by descendants by default.', max_length=32, verbose_name='Protocol Family Mode'),
        ),
    ]
