# Generated by Django 5.2.13 on 2026-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsDashboardProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reports Dashboard',
                'verbose_name_plural': 'Reports Dashboard',
                'managed': False,
            },
        ),
    ]
