# Generated by Django 5.0.3 on 2025-05-13 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Access Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('permissions', models.JSONField(default=dict, help_text='JSON with access permissions (read, book, write)', verbose_name='Permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses_by', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Granted To')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Pet Access',
                'verbose_name_plural': 'Pet Accesses',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.petaccess', verbose_name='Access')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(max_length=50, verbose_name='Access Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Granted To')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Access',
                'verbose_name_plural': 'Accesses',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'granted_to', 'access_type')},
            },
        ),
        migrations.AddIndex(
            model_name='petaccess',
            index=models.Index(fields=['token'], name='access_peta_token_0e96b9_idx'),
        ),
        migrations.AddIndex(
            model_name='petaccess',
            index=models.Index(fields=['expires_at'], name='access_peta_expires_e62562_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='petaccess',
            unique_together={('pet', 'granted_to')},
        ),
    ]
