# Generated by Django 5.2.10 on 2026-01-12 13:16

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0015_billingconfig'),
        ('providers', '0018_add_public_offer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for document type (e.g., "global_offer", "privacy_policy")', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Human-readable name (e.g., "Global Offer", "Privacy Policy")', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of this document type', verbose_name='Description')),
                ('requires_billing_config', models.BooleanField(default=False, help_text='Whether this document type requires billing configuration (e.g., Global Offer)', verbose_name='Requires Billing Config')),
                ('requires_region_code', models.BooleanField(default=False, help_text='Whether this document type requires region code (e.g., Regional Addendum)', verbose_name='Requires Region Code')),
                ('requires_addendum_type', models.BooleanField(default=False, help_text='Whether this document type requires addendum type (e.g., Regional Addendum)', verbose_name='Requires Addendum Type')),
                ('allows_variables', models.BooleanField(default=False, help_text='Whether this document type allows custom variables (e.g., {{vat_rate}})', verbose_name='Allows Variables')),
                ('is_required_for_all_countries', models.BooleanField(default=False, help_text='Whether this document type is required for all countries (e.g., Global Offer)', verbose_name='Required for All Countries')),
                ('is_multiple_allowed', models.BooleanField(default=False, help_text='Whether multiple documents of this type can be assigned to one country (e.g., Regional Addendums)', verbose_name='Multiple Allowed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document type is currently active', verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in admin and API', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Legal Document Type',
                'verbose_name_plural': 'Legal Document Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version of the document (e.g., 1.0, 1.1)', max_length=20, verbose_name='Version')),
                ('title', models.CharField(help_text='Title of the document', max_length=200, verbose_name='Title')),
                ('region_code', models.CharField(blank=True, choices=[('EU', 'European Union'), ('EEA', 'European Economic Area'), ('RU', 'Russian Federation'), ('UA', 'Ukraine'), ('EAEU', 'Eurasian Economic Union'), ('US', 'United States')], help_text='Region code (only for regional addendums)', max_length=10, null=True, verbose_name='Region Code')),
                ('addendum_type', models.CharField(blank=True, choices=[('tax', 'Tax and VAT'), ('data_protection', 'Data Protection (GDPR, etc.)'), ('fiscal', 'Fiscal Requirements'), ('consumer_protection', 'Consumer Protection'), ('other', 'Other')], help_text='Type of addendum (only for regional addendums)', max_length=20, null=True, verbose_name='Addendum Type')),
                ('variables', models.JSONField(blank=True, help_text='Additional variables for this document. Example: {"vat_rate": "20", "fiscal_law": "54-ФЗ"}', null=True, verbose_name='Variables')),
                ('effective_date', models.DateField(help_text='Date when this document becomes effective', verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is currently active', verbose_name='Is Active')),
                ('change_notification_days', models.PositiveIntegerField(default=30, help_text='Days before effective_date to notify about document changes. Minimum: 30 days.', verbose_name='Change Notification Days')),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When notification about document changes was sent', null=True, verbose_name='Notification Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('billing_config', models.ForeignKey(blank=True, help_text='Billing configuration (only for document types that require it)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingconfig', verbose_name='Billing Config')),
                ('document_type', models.ForeignKey(help_text='Type of legal document', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='legal.legaldocumenttype', verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-effective_date', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='CountryLegalConfig',
            fields=[
                ('country', django_countries.fields.CountryField(help_text='Country code (ISO 3166-1 alpha-2)', max_length=2, primary_key=True, serialize=False, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cookie_policy', models.ForeignKey(blank=True, help_text='Cookie Policy for this country', limit_choices_to={'document_type__code': 'cookie_policy', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_configs_cookie', to='legal.legaldocument', verbose_name='Cookie Policy')),
                ('global_offer', models.ForeignKey(help_text='Global offer (same for all providers)', limit_choices_to={'document_type__code': 'global_offer', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='country_configs_global', to='legal.legaldocument', verbose_name='Global Offer')),
                ('privacy_policy', models.ForeignKey(blank=True, help_text='Privacy Policy for this country', limit_choices_to={'document_type__code': 'privacy_policy', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_configs_privacy', to='legal.legaldocument', verbose_name='Privacy Policy')),
                ('regional_addendums', models.ManyToManyField(blank=True, help_text='Regional addendums required for this country', limit_choices_to={'document_type__code': 'regional_addendum', 'is_active': True}, related_name='country_configs_regional', to='legal.legaldocument', verbose_name='Regional Addendums')),
                ('terms_of_service', models.ForeignKey(blank=True, help_text='Terms of Service for this country', limit_choices_to={'document_type__code': 'terms_of_service', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_configs_terms', to='legal.legaldocument', verbose_name='Terms of Service')),
            ],
            options={
                'verbose_name': 'Country Legal Config',
                'verbose_name_plural': 'Country Legal Configs',
            },
        ),
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sr', 'Montenegrin'), ('de', 'German')], help_text='Language code (e.g., en, ru, de, sr)', max_length=10, verbose_name='Language')),
                ('content_docx_file', models.FileField(blank=True, help_text='Upload DOCX file for this language. Will be converted to HTML automatically.', null=True, upload_to='legal/documents/%Y/%m/%d/', verbose_name='Content DOCX File')),
                ('content', models.TextField(blank=True, help_text='HTML content, auto-converted from DOCX file. Can contain variables like {{commission_percent}}.', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document', models.ForeignKey(help_text='Legal document this translation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='legal.legaldocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document Translation',
                'verbose_name_plural': 'Document Translations',
                'ordering': ['language'],
                'unique_together': {('document', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_version', models.CharField(help_text='Version of the document that was accepted', max_length=20, verbose_name='Document Version')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the document was accepted', verbose_name='Accepted At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the document was accepted', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent (browser/device) from which the document was accepted', verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this acceptance is currently active', verbose_name='Is Active')),
                ('provider', models.ForeignKey(blank=True, help_text='Provider who accepted the document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_acceptances', to='providers.provider', verbose_name='Provider')),
                ('user', models.ForeignKey(blank=True, help_text='User who accepted the document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('document', models.ForeignKey(help_text='Legal document that was accepted', on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document Acceptance',
                'verbose_name_plural': 'Document Acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'document', 'is_active'], name='legal_docum_user_id_2f1220_idx'), models.Index(fields=['provider', 'document', 'is_active'], name='legal_docum_provide_727ee1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', 'is_active'], name='legal_legal_documen_92cdce_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['region_code', 'is_active'], name='legal_legal_region__3d47ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together={('document_type', 'version')},
        ),
    ]
