# Generated by Django 5.2.10 on 2026-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='title_de',
            field=models.CharField(help_text='Title of the document', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_en',
            field=models.CharField(help_text='Title of the document', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_ru',
            field=models.CharField(help_text='Title of the document', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_sr',
            field=models.CharField(help_text='Title of the document', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description of this document type', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of this document type', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Description of this document type', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='description_sr',
            field=models.TextField(blank=True, help_text='Description of this document type', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='name_de',
            field=models.CharField(help_text='Human-readable name (e.g., "Global Offer", "Privacy Policy")', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='name_en',
            field=models.CharField(help_text='Human-readable name (e.g., "Global Offer", "Privacy Policy")', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='name_ru',
            field=models.CharField(help_text='Human-readable name (e.g., "Global Offer", "Privacy Policy")', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='name_sr',
            field=models.CharField(help_text='Human-readable name (e.g., "Global Offer", "Privacy Policy")', max_length=200, null=True, verbose_name='Name'),
        ),
    ]
