# Generated by Django 5.2.10 on 2026-01-12 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_remove_public_offer_regional_addendum'),
        ('providers', '0018_add_public_offer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacceptance',
            name='accepted_addendums_documents',
            field=models.ManyToManyField(blank=True, help_text='Regional addendums (LegalDocument) that were accepted with this offer (only for global_offer)', limit_choices_to={'document_type__code': 'regional_addendum', 'is_active': True}, related_name='acceptances_addendums', to='legal.legaldocument', verbose_name='Accepted Regional Addendums'),
        ),
        migrations.AddField(
            model_name='documentacceptance',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='User who accepted the document (for provider offers - this is the Owner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_documents', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AlterField(
            model_name='documentacceptance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this acceptance is currently active (if document is updated, old acceptances become inactive)', verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='documentacceptance',
            index=models.Index(fields=['provider', 'is_active'], name='legal_docum_provide_79cd81_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptance',
            index=models.Index(fields=['document', 'is_active'], name='legal_docum_documen_f04c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptance',
            index=models.Index(fields=['accepted_at'], name='legal_docum_accepte_44f369_idx'),
        ),
    ]
