# Generated by Django 5.2.10 on 2026-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_add_side_letter_fields'),
        ('legal', '0003_documentacceptance_accepted_addendums_documents_and_more'),
        ('providers', '0018_add_public_offer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='activity_bonus_enabled',
            field=models.BooleanField(default=False, help_text='Enable activity-based bonuses', verbose_name='Activity Bonus Enabled'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='activity_bonus_rules',
            field=models.JSONField(blank=True, help_text='Activity bonus rules. Example: [{"min_rating": 4.5, "bonus_percent": 0.5}, {"min_bookings_per_month": 50, "bonus_percent": 1}]', null=True, verbose_name='Activity Bonus Rules'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='commission_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed commission amount per booking (if commission_type is "fixed" or "hybrid")', max_digits=12, null=True, verbose_name='Fixed Commission Amount'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='commission_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum commission amount per booking', max_digits=12, null=True, verbose_name='Maximum Commission'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='commission_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum commission amount (e.g., 50 rubles minimum even if 5% is less)', max_digits=12, null=True, verbose_name='Minimum Commission'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage (if commission_type is "percent" or "hybrid")', max_digits=5, null=True, verbose_name='Commission Percentage'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount'), ('hybrid', 'Hybrid'), ('tiered', 'Tiered')], help_text='Type of commission calculation', max_length=20, null=True, verbose_name='Commission Type'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='debt_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Debt threshold for blocking (overrides default)', max_digits=12, null=True, verbose_name='Debt Threshold'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Scanned signed Side Letter document', null=True, upload_to='legal/side_letters/%Y/%m/%d/', verbose_name='Document File'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='modified_clauses',
            field=models.JSONField(blank=True, help_text='Modified clauses from the offer. Example: {"5.1": "Commission 5% instead of 10%", "4.3": "Payment deferral 10 days instead of 5"}', null=True, verbose_name='Modified Clauses'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='overdue_threshold_1',
            field=models.PositiveIntegerField(blank=True, help_text='Days overdue for information notification (overrides default)', null=True, verbose_name='Overdue Threshold 1'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='overdue_threshold_2',
            field=models.PositiveIntegerField(blank=True, help_text='Days overdue for exclusion from search (overrides default)', null=True, verbose_name='Overdue Threshold 2'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='overdue_threshold_3',
            field=models.PositiveIntegerField(blank=True, help_text='Days overdue for full blocking (overrides default)', null=True, verbose_name='Overdue Threshold 3'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='payment_deferral_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment deferral days (overrides default from offer)', null=True, verbose_name='Payment Deferral Days'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='providers',
            field=models.ManyToManyField(blank=True, help_text='Providers associated with this document (for Side Letter)', related_name='legal_documents', to='providers.provider', verbose_name='Providers'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='Date when Side Letter was signed', null=True, verbose_name='Signed At'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='tiered_rates',
            field=models.JSONField(blank=True, help_text='Tiered commission rates. Example: [{"min": 0, "max": 10000, "percent": 10}, {"min": 10000, "max": 50000, "percent": 8}, {"min": 50000, "percent": 5}]', null=True, verbose_name='Tiered Rates'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='volume_discount_enabled',
            field=models.BooleanField(default=False, help_text='Enable volume-based discounts', verbose_name='Volume Discount Enabled'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='volume_discount_rules',
            field=models.JSONField(blank=True, help_text='Volume discount rules. Example: [{"min_bookings": 100, "discount_percent": 1}, {"min_bookings": 500, "discount_percent": 2}]', null=True, verbose_name='Volume Discount Rules'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='allows_financial_terms',
            field=models.BooleanField(default=False, help_text='Whether this document type allows financial terms (commissions, deferrals, thresholds)', verbose_name='Allows Financial Terms'),
        ),
        migrations.AddField(
            model_name='legaldocumenttype',
            name='requires_provider',
            field=models.BooleanField(default=False, help_text='Whether this document type requires a provider (e.g., Side Letter)', verbose_name='Requires Provider'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['signed_at'], name='legal_legal_signed__8c243e_idx'),
        ),
    ]
