# Generated by Django 5.2.10 on 2026-01-15 15:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_create_side_letter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='HTML content. Can be edited directly or auto-converted from DOCX file. Can contain variables like {{commission_percent}}.', verbose_name='Content'),
        ),
    ]
