# Generated by Django 5.2.10 on 2026-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_add_side_letter_fields'),
        ('legal', '0007_remove_old_translation_fields'),
        ('providers', '0019_add_vat_verification_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('me', 'Montenegrin'), ('de', 'German')], help_text='Language code (e.g., en, ru, de, sr)', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='variables',
            field=models.JSONField(blank=True, help_text='Additional variables for this document. Example: {"vat_rate": "20", "fiscal_law": "Law 54-FZ"}', null=True, verbose_name='Variables'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('region_code__isnull', False)), fields=('document_type', 'version', 'region_code'), name='legal_document_unique_with_region'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('region_code__isnull', True)), fields=('document_type', 'version'), name='legal_document_unique_without_region'),
        ),
    ]
