# Generated by Django 5.2.5 on 2026-01-01 17:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_fix_all_fk_to_users_user'),
        ('providers', '0017_locationschedule_delete_providerschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSpecialTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount'), ('hybrid', 'Hybrid'), ('tiered', 'Tiered')], default='percent', help_text='Type of commission calculation', max_length=20, verbose_name='Commission Type')),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage (if commission_type is "percent" or "hybrid")', max_digits=5, null=True, verbose_name='Commission Percentage')),
                ('commission_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed commission amount per booking (if commission_type is "fixed" or "hybrid")', max_digits=12, null=True, verbose_name='Fixed Commission Amount')),
                ('commission_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum commission amount (e.g., 50 rubles minimum even if 5% is less)', max_digits=12, null=True, verbose_name='Minimum Commission')),
                ('commission_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum commission amount per booking', max_digits=12, null=True, verbose_name='Maximum Commission')),
                ('tiered_rates', models.JSONField(blank=True, help_text='Tiered commission rates. Example: [{"min": 0, "max": 10000, "percent": 10}, {"min": 10000, "max": 50000, "percent": 8}, {"min": 50000, "percent": 5}]', null=True, verbose_name='Tiered Rates')),
                ('payment_deferral_days', models.PositiveIntegerField(blank=True, help_text='Payment deferral days (overrides default from offer)', null=True, verbose_name='Payment Deferral Days')),
                ('debt_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Debt threshold for blocking (overrides default)', max_digits=12, null=True, verbose_name='Debt Threshold')),
                ('overdue_threshold_1', models.PositiveIntegerField(blank=True, help_text='Days overdue for information notification (overrides default)', null=True, verbose_name='Overdue Threshold 1')),
                ('overdue_threshold_2', models.PositiveIntegerField(blank=True, help_text='Days overdue for exclusion from search (overrides default)', null=True, verbose_name='Overdue Threshold 2')),
                ('overdue_threshold_3', models.PositiveIntegerField(blank=True, help_text='Days overdue for full blocking (overrides default)', null=True, verbose_name='Overdue Threshold 3')),
                ('volume_discount_enabled', models.BooleanField(default=False, help_text='Enable volume-based discounts', verbose_name='Volume Discount Enabled')),
                ('volume_discount_rules', models.JSONField(blank=True, help_text='Volume discount rules. Example: [{"min_bookings": 100, "discount_percent": 1}, {"min_bookings": 500, "discount_percent": 2}]', null=True, verbose_name='Volume Discount Rules')),
                ('activity_bonus_enabled', models.BooleanField(default=False, help_text='Enable activity-based bonuses', verbose_name='Activity Bonus Enabled')),
                ('activity_bonus_rules', models.JSONField(blank=True, help_text='Activity bonus rules. Example: [{"min_rating": 4.5, "bonus_percent": 0.5}, {"min_bookings_per_month": 50, "bonus_percent": 1}]', null=True, verbose_name='Activity Bonus Rules')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about special terms', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these special terms are active', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_terms', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('provider', models.OneToOneField(help_text='Provider with special terms', on_delete=django.db.models.deletion.CASCADE, related_name='special_terms', to='providers.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Provider Special Terms',
                'verbose_name_plural': 'Provider Special Terms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionalAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(choices=[('EU', 'European Union'), ('EEA', 'European Economic Area'), ('RU', 'Russian Federation'), ('UA', 'Ukraine'), ('EAEU', 'Eurasian Economic Union'), ('US', 'United States')], help_text='Region code (EU, RU, UA, etc.)', max_length=10, verbose_name='Region Code')),
                ('addendum_type', models.CharField(choices=[('tax', 'Tax and VAT'), ('data_protection', 'Data Protection (GDPR, etc.)'), ('fiscal', 'Fiscal Requirements'), ('consumer_protection', 'Consumer Protection'), ('other', 'Other')], default='other', help_text='Type of addendum (tax, data protection, fiscal, etc.)', max_length=20, verbose_name='Addendum Type')),
                ('region_name', models.CharField(help_text='Human-readable region name', max_length=100, verbose_name='Region Name')),
                ('version', models.CharField(help_text='Version of the addendum (1.0, 1.1, etc.)', max_length=20, verbose_name='Version')),
                ('title', models.CharField(help_text='Title of the regional addendum', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc.', verbose_name='Content')),
                ('variables', models.JSONField(blank=True, help_text='Additional variables for this addendum. Example: {"vat_rate": "20", "fiscal_law": "54-ФЗ"}', null=True, verbose_name='Variables')),
                ('effective_date', models.DateField(help_text='Date when this addendum becomes effective', verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this addendum is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Regional Addendum',
                'verbose_name_plural': 'Regional Addendums',
                'ordering': ['region_code', 'addendum_type', '-effective_date'],
                'indexes': [models.Index(fields=['region_code', 'is_active'], name='billing_reg_region__fddd85_idx'), models.Index(fields=['addendum_type', 'is_active'], name='billing_reg_addendu_9d3e07_idx')],
                'unique_together': {('region_code', 'addendum_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version of the offer (1.0, 1.1, etc.)', max_length=20, verbose_name='Version')),
                ('title', models.CharField(help_text='Title of the public offer', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage.', verbose_name='Content')),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default commission percentage (e.g., 5.00 for 5%). This value is substituted into offer text as {{commission_percent}}.', max_digits=5, verbose_name='Default Commission Percentage')),
                ('default_payment_deferral_days', models.PositiveIntegerField(default=5, help_text='Default payment deferral days after service completion. Used in offer text as {{payment_deferral_days}}', verbose_name='Default Payment Deferral Days')),
                ('default_invoice_period_days', models.PositiveIntegerField(default=3, help_text='Days to generate invoice after period end. Used in offer text as {{invoice_period_days}}', verbose_name='Default Invoice Period Days')),
                ('effective_date', models.DateField(help_text='Date when this offer becomes effective', verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this offer is currently active', verbose_name='Is Active')),
                ('change_notification_days', models.PositiveIntegerField(default=90, help_text='Days before effective_date to notify providers about offer changes. CRITICAL: Must be at least 90 days (3 months) when commission_percent changes.', verbose_name='Change Notification Days')),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When notification about offer changes was sent to providers', null=True, verbose_name='Notification Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('regional_addendums', models.ManyToManyField(blank=True, help_text='Regional addendums that apply to this offer', related_name='offers', to='billing.regionaladdendum', verbose_name='Regional Addendums')),
            ],
            options={
                'verbose_name': 'Public Offer',
                'verbose_name_plural': 'Public Offers',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProviderOfferAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the offer was accepted', verbose_name='Accepted At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the offer was accepted (for audit and legal protection)', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent from which the offer was accepted (for audit)', verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, help_text='If offer is updated, old acceptances become inactive', verbose_name='Is Active')),
                ('accepted_by', models.ForeignKey(help_text='User who accepted the offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_offers', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_acceptances', to='providers.provider', verbose_name='Provider')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='billing.publicoffer', verbose_name='Public Offer')),
                ('accepted_addendums', models.ManyToManyField(blank=True, help_text='Regional addendums that were accepted with this offer', related_name='acceptances', to='billing.regionaladdendum', verbose_name='Accepted Addendums')),
            ],
            options={
                'verbose_name': 'Provider Offer Acceptance',
                'verbose_name_plural': 'Provider Offer Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='SideLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_clauses', models.JSONField(help_text='Modified clauses from the offer. Example: {"5.1": "Commission 5% instead of 10%", "4.3": "Payment deferral 10 days instead of 5"}', verbose_name='Modified Clauses')),
                ('document', models.FileField(help_text='Scanned signed Side Letter document', upload_to='side_letters/%Y/%m/%d/', verbose_name='Document')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Date when Side Letter was signed', null=True, verbose_name='Signed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this Side Letter is active', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_side_letters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='side_letters', to='billing.publicoffer', verbose_name='Public Offer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_letters', to='providers.provider', verbose_name='Provider')),
                ('special_terms', models.OneToOneField(blank=True, help_text='Special terms created from this Side Letter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_letter', to='billing.providerspecialterms', verbose_name='Special Terms')),
            ],
            options={
                'verbose_name': 'Side Letter',
                'verbose_name_plural': 'Side Letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providerspecialterms',
            index=models.Index(fields=['provider', 'is_active'], name='billing_pro_provide_710e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicoffer',
            index=models.Index(fields=['is_active', 'effective_date'], name='billing_pub_is_acti_409afb_idx'),
        ),
        migrations.AddIndex(
            model_name='publicoffer',
            index=models.Index(fields=['version'], name='billing_pub_version_9ecc11_idx'),
        ),
        migrations.AddIndex(
            model_name='providerofferacceptance',
            index=models.Index(fields=['provider', 'is_active'], name='billing_pro_provide_21c52a_idx'),
        ),
        migrations.AddIndex(
            model_name='providerofferacceptance',
            index=models.Index(fields=['offer', 'is_active'], name='billing_pro_offer_i_140406_idx'),
        ),
        migrations.AddIndex(
            model_name='providerofferacceptance',
            index=models.Index(fields=['accepted_at'], name='billing_pro_accepte_9b28e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sideletter',
            index=models.Index(fields=['provider', 'is_active'], name='billing_sid_provide_364592_idx'),
        ),
        migrations.AddIndex(
            model_name='sideletter',
            index=models.Index(fields=['offer', 'is_active'], name='billing_sid_offer_i_39ffba_idx'),
        ),
    ]
