# Generated by Django 5.2.5 on 2026-01-02 09:53

from django.db import migrations


class Migration(migrations.Migration):
    """
    Миграция для удаления таблиц Contract из базы данных.
    
    Удаляет:
    1. FK contract из PaymentHistory
    2. Все таблицы Contract (Contract, ContractType, ContractCommission, ContractDiscount, ContractApprovalHistory)
    
    Порядок удаления важен из-за внешних ключей:
    - Сначала удаляем FK из PaymentHistory
    - Затем удаляем зависимые таблицы (ContractCommission, ContractDiscount, ContractApprovalHistory)
    - Затем удаляем Contract
    - В конце удаляем ContractType
    """

    dependencies = [
        ('billing', '0005_update_payment_history_for_offers'),
    ]

    operations = [
        # Шаг 1: Удаляем FK contract из PaymentHistory
        # Это поле уже nullable, но FK еще существует в БД
        migrations.RemoveField(
            model_name='paymenthistory',
            name='contract',
        ),
        
        # Шаг 2: Удаляем зависимые таблицы (сначала те, что зависят от Contract)
        migrations.DeleteModel(
            name='ContractApprovalHistory',
        ),
        migrations.DeleteModel(
            name='ContractCommission',
        ),
        migrations.DeleteModel(
            name='ContractDiscount',
        ),
        
        # Шаг 3: Удаляем основную таблицу Contract
        migrations.DeleteModel(
            name='Contract',
        ),
        
        # Шаг 4: Удаляем ContractType (последним, так как Contract зависит от него)
        migrations.DeleteModel(
            name='ContractType',
        ),
    ]
