# Generated by Django 5.2.5 on 2026-01-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_contract_tables'),
        ('providers', '0018_add_public_offer_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this payment is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', to='billing.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='offer_acceptance',
            field=models.ForeignKey(blank=True, help_text='Offer acceptance this payment is related to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', to='billing.providerofferacceptance', verbose_name='Offer Acceptance'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='provider',
            field=models.ForeignKey(help_text='Provider for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='providers.provider', verbose_name='Provider'),
        ),
    ]
