# Generated by Django 5.2.5 on 2026-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_paymenthistory_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicoffer',
            name='content_de_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for German version. Will be converted to HTML automatically.', null=True, upload_to='offers/%Y/%m/%d/', verbose_name='Content DE (DOCX)'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_en_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for English version. Will be converted to HTML automatically.', null=True, upload_to='offers/%Y/%m/%d/', verbose_name='Content EN (DOCX)'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_me_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for Montenegrin version. Will be converted to HTML automatically.', null=True, upload_to='offers/%Y/%m/%d/', verbose_name='Content ME (DOCX)'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_ru_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for Russian version. Will be converted to HTML automatically.', null=True, upload_to='offers/%Y/%m/%d/', verbose_name='Content RU (DOCX)'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_de_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for German version. Will be converted to HTML automatically.', null=True, upload_to='addendums/%Y/%m/%d/', verbose_name='Content DE (DOCX)'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_en_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for English version. Will be converted to HTML automatically.', null=True, upload_to='addendums/%Y/%m/%d/', verbose_name='Content EN (DOCX)'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_me_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for Montenegrin version. Will be converted to HTML automatically.', null=True, upload_to='addendums/%Y/%m/%d/', verbose_name='Content ME (DOCX)'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_ru_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for Russian version. Will be converted to HTML automatically.', null=True, upload_to='addendums/%Y/%m/%d/', verbose_name='Content RU (DOCX)'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='regionaladdendum',
            name='content',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported.', verbose_name='Content'),
        ),
    ]
