# Generated by Django 5.2.5 on 2026-01-03 18:58

import django_countries.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_docx_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='total_with_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission amount including VAT', max_digits=12, verbose_name='Total with VAT'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT amount added to commission', max_digits=12, verbose_name='VAT Amount'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT rate percentage (e.g., 20.00 for 20%)', max_digits=5, null=True, verbose_name='VAT Rate'),
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(help_text='Country code (ISO 3166-1 alpha-2)', max_length=2, verbose_name='Country')),
                ('rate', models.DecimalField(decimal_places=2, help_text='VAT rate percentage (e.g., 20.00 for 20%)', max_digits=5, verbose_name='VAT Rate')),
                ('effective_date', models.DateField(help_text='Date when this VAT rate becomes effective', verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this VAT rate is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'ordering': ['country', '-effective_date'],
                'indexes': [models.Index(fields=['country', 'is_active'], name='billing_vat_country_bcd2b1_idx'), models.Index(fields=['effective_date'], name='billing_vat_effecti_8c9881_idx')],
                'unique_together': {('country', 'effective_date')},
            },
        ),
    ]
