# Generated by Django 5.2.5 on 2026-01-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_vat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicoffer',
            name='content_de',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_en',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_me',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_ru',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='title_de',
            field=models.CharField(help_text='Title of the public offer', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='title_en',
            field=models.CharField(help_text='Title of the public offer', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='title_me',
            field=models.CharField(help_text='Title of the public offer', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='title_ru',
            field=models.CharField(help_text='Title of the public offer', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_de',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_en',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_me',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_ru',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='title_de',
            field=models.CharField(help_text='Title of the regional addendum', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='title_en',
            field=models.CharField(help_text='Title of the regional addendum', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='title_me',
            field=models.CharField(help_text='Title of the regional addendum', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='title_ru',
            field=models.CharField(help_text='Title of the regional addendum', max_length=200, null=True, verbose_name='Title'),
        ),
    ]
