# Generated by Django 5.2.5 on 2026-01-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_publicoffer_content_de_publicoffer_content_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicoffer',
            old_name='content_me',
            new_name='content_sr',
        ),
        migrations.RenameField(
            model_name='publicoffer',
            old_name='title_me',
            new_name='title_sr',
        ),
        migrations.RenameField(
            model_name='regionaladdendum',
            old_name='content_me',
            new_name='content_sr',
        ),
        migrations.RenameField(
            model_name='regionaladdendum',
            old_name='title_me',
            new_name='title_sr',
        ),
    ]
