# Generated by Django 5.2.5 on 2026-01-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_rename_me_to_sr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicoffer',
            name='content_me_file',
        ),
        migrations.RemoveField(
            model_name='regionaladdendum',
            name='content_me_file',
        ),
        migrations.AddField(
            model_name='publicoffer',
            name='content_sr_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for Montenegrin version. Will be converted to HTML automatically.', null=True, upload_to='offers/%Y/%m/%d/', verbose_name='Content SR (DOCX)'),
        ),
        migrations.AddField(
            model_name='regionaladdendum',
            name='content_sr_file',
            field=models.FileField(blank=True, help_text='Upload DOCX file for Montenegrin version. Will be converted to HTML automatically.', null=True, upload_to='addendums/%Y/%m/%d/', verbose_name='Content SR (DOCX)'),
        ),
    ]
