# Generated by Django 5.2.5 on 2026-01-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_rename_me_file_to_sr_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicoffer',
            name='regional_addendums',
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content_de',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content_en',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content_ru',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content_sr',
            field=models.TextField(help_text='Offer text with variables. Use {{commission_percent}} for commission percentage. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='regionaladdendum',
            name='content',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='regionaladdendum',
            name='content_de',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='regionaladdendum',
            name='content_en',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='regionaladdendum',
            name='content_ru',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='regionaladdendum',
            name='content_sr',
            field=models.TextField(help_text='Content of the regional addendum. Can contain variables like {{commission_percent}}, {{vat_rate}}, etc. HTML format supported. Use "Convert DOCX files" button to fill from uploaded DOCX files.', null=True, verbose_name='Content'),
        ),
    ]
