# Generated by Django 5.2.5 on 2026-01-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_remove_regional_addendums_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicoffer',
            name='change_notification_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before effective_date to notify providers about offer changes. Minimum: 30 days. This value can be used in offer text as {{change_notification_days}}.', verbose_name='Change Notification Days'),
        ),
    ]
