# Generated by Django 5.2.10 on 2026-01-12 13:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_change_notification_days_minimum_30'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this billing configuration', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of this billing configuration', verbose_name='Description')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Commission percentage (e.g., 5.00 for 5%). This value is substituted into offer text as {{commission_percent}}.', max_digits=5, verbose_name='Commission Percentage')),
                ('payment_deferral_days', models.PositiveIntegerField(default=5, help_text='Payment deferral days after service completion. Used in offer text as {{payment_deferral_days}}', verbose_name='Payment Deferral Days')),
                ('invoice_period_days', models.PositiveIntegerField(default=3, help_text='Days to generate invoice after period end. Used in offer text as {{invoice_period_days}}', verbose_name='Invoice Period Days')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this billing configuration is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Billing Config',
                'verbose_name_plural': 'Billing Configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
