# Generated by Django 5.2.10 on 2026-01-12 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_billingconfig'),
        ('legal', '0001_initial'),
        ('providers', '0018_add_public_offer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerofferacceptance',
            name='accepted_addendums_documents',
            field=models.ManyToManyField(blank=True, help_text='Regional addendums (LegalDocument) that were accepted with this offer', limit_choices_to={'document_type__code': 'regional_addendum', 'is_active': True}, related_name='provider_acceptances_addendums', to='legal.legaldocument', verbose_name='Accepted Regional Addendums (Documents)'),
        ),
        migrations.AddField(
            model_name='providerofferacceptance',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Legal document (Global Offer) that was accepted', limit_choices_to={'document_type__code': 'global_offer', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_acceptances', to='legal.legaldocument', verbose_name='Legal Document'),
        ),
        migrations.AlterField(
            model_name='providerofferacceptance',
            name='accepted_addendums',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Use accepted_addendums_documents instead. Kept for backward compatibility.', related_name='acceptances', to='billing.regionaladdendum', verbose_name='Accepted Addendums (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='providerofferacceptance',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use document field instead. Kept for backward compatibility.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='billing.publicoffer', verbose_name='Public Offer (Deprecated)'),
        ),
        migrations.AddIndex(
            model_name='providerofferacceptance',
            index=models.Index(fields=['document', 'is_active'], name='billing_pro_documen_40a873_idx'),
        ),
    ]
