# Generated by Django 5.2.10 on 2026-01-12 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_providerofferacceptance_accepted_addendums_documents_and_more'),
        ('legal', '0002_remove_public_offer_regional_addendum'),
        ('providers', '0018_add_public_offer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerofferacceptance',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='sideletter',
            name='offer',
        ),
        migrations.AlterUniqueTogether(
            name='regionaladdendum',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='providerofferacceptance',
            name='accepted_addendums',
        ),
        migrations.RemoveIndex(
            model_name='providerofferacceptance',
            name='billing_pro_offer_i_140406_idx',
        ),
        migrations.RemoveIndex(
            model_name='sideletter',
            name='billing_sid_offer_i_39ffba_idx',
        ),
        migrations.AddField(
            model_name='sideletter',
            name='legal_document',
            field=models.ForeignKey(blank=True, help_text='Legal document (Global Offer) that this Side Letter modifies', limit_choices_to={'document_type__code': 'global_offer', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='side_letters', to='legal.legaldocument', verbose_name='Legal Document'),
        ),
        migrations.AddIndex(
            model_name='sideletter',
            index=models.Index(fields=['legal_document', 'is_active'], name='billing_sid_legal_d_2309a7_idx'),
        ),
        migrations.DeleteModel(
            name='PublicOffer',
        ),
        migrations.DeleteModel(
            name='RegionalAddendum',
        ),
    ]
