# Generated by Django 5.2.10 on 2026-01-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_remove_public_offer_regional_addendum'),
        ('legal', '0002_remove_public_offer_regional_addendum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='offer_acceptance',
            field=models.ForeignKey(blank=True, help_text='Document acceptance this payment is related to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', to='legal.documentacceptance', verbose_name='Offer Acceptance'),
        ),
        migrations.DeleteModel(
            name='ProviderOfferAcceptance',
        ),
    ]
