# Generated by Django 5.2.10 on 2026-01-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_paymenthistory_offer_acceptance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideletter',
            name='special_terms',
        ),
        migrations.RemoveField(
            model_name='sideletter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sideletter',
            name='legal_document',
        ),
        migrations.RemoveField(
            model_name='sideletter',
            name='provider',
        ),
        migrations.DeleteModel(
            name='ProviderSpecialTerms',
        ),
        migrations.DeleteModel(
            name='SideLetter',
        ),
    ]
