# Generated by Django 5.2.11 on 2026-03-19 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_blockingtemplate_location_to_providerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockingschedule',
            name='time',
            field=models.TimeField(default=datetime.time(2, 0), help_text='Time of day to perform checks (HH:MM format)', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='blockingsystemsettings',
            name='check_time',
            field=models.TimeField(default=datetime.time(2, 0), help_text='Time of day to perform checks (HH:MM format)', verbose_name='Check Time'),
        ),
    ]
