# Generated by Django 5.2.11 on 2026-03-23 11:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_blockingschedule_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Paid Amount'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Refunded Amount'),
        ),
        migrations.AddField(
            model_name='providerblocking',
            name='blocking_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Blocking level from 1 (warning) to 3 (full block)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Blocking Level'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
