# Generated by Django 5.2.11 on 2026-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_paymenthistory_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Billing Reports',
                'verbose_name_plural': 'Billing Reports',
                'managed': False,
            },
        ),
    ]
