# Generated by Django 5.2.11 on 2026-03-25 15:16

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


def seed_dummy_platform_company(apps, schema_editor):
    """Создает тестовое юрлицо платформы, чтобы инвойсы могли генерироваться сразу после миграции."""
    PlatformCompany = apps.get_model('billing', 'PlatformCompany')
    PlatformCompanyCountry = apps.get_model('billing', 'PlatformCompanyCountry')

    if PlatformCompany.objects.exists():
        return

    company = PlatformCompany.objects.create(
        name='PetCare Demo Billing Ltd.',
        address='Demo address 1, Podgorica, Montenegro',
        tax_id='DEMO-TAX-48291',
        iban='ME25505000012345678951',
        bic='DEMOMEPG',
        swift='DEMOMEPG',
        bank_name='Demo Bank',
        is_active=True,
    )
    montenegro = PlatformCompanyCountry.objects.create(country='ME')
    company.countries.add(montenegro)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_billingreport'),
        ('booking', '0014_bookingautocompletesettings_manual_booking_emergency_window_hours'),
        ('providers', '0049_providerreportexportjob_downloaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal entity name used in invoices', max_length=255, verbose_name='Name')),
                ('address', models.TextField(help_text='Registered legal address used in invoices', verbose_name='Address')),
                ('tax_id', models.CharField(help_text='Tax identification number of the platform company', max_length=128, verbose_name='Tax ID')),
                ('iban', models.CharField(blank=True, help_text='IBAN for incoming invoice payments', max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, help_text='BIC or local bank identifier', max_length=32, verbose_name='BIC')),
                ('swift', models.CharField(blank=True, help_text='SWIFT code of the bank', max_length=32, verbose_name='SWIFT')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name used in invoices', max_length=255, verbose_name='Bank Name')),
                ('seal_scan', models.ImageField(blank=True, help_text='Optional scan of the company seal', null=True, upload_to='billing/platform_companies/seals/%Y/%m/%d/', verbose_name='Seal Scan')),
                ('signature_scan', models.ImageField(blank=True, help_text='Optional scan of the company signature', null=True, upload_to='billing/platform_companies/signatures/%Y/%m/%d/', verbose_name='Signature Scan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company can be used for new invoices', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Platform Company',
                'verbose_name_plural': 'Platform Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformCompanyCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(help_text='Country code (ISO 3166-1 alpha-2)', max_length=2, unique=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Platform Company Country',
                'verbose_name_plural': 'Platform Company Countries',
                'ordering': ['country'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='billing/invoices/%Y/%m/%d/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='payment',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was applied to invoices', null=True, verbose_name='Applied At'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Specific invoice to apply this payment to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for reconciliation', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Provider for whom the payment was received', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking', verbose_name='Booking'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('booking',), name='billing_invoice_line_unique_booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_company',
            field=models.ForeignKey(blank=True, help_text='Platform legal entity used for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.platformcompany', verbose_name='Platform Company'),
        ),
        migrations.AddField(
            model_name='platformcompany',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Countries served by this platform legal entity', related_name='platform_companies', to='billing.platformcompanycountry', verbose_name='Countries'),
        ),
        migrations.RunPython(seed_dummy_platform_company, migrations.RunPython.noop),
    ]
