# Generated by Django 5.2.11 on 2026-04-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_platformcompany_platformcompanycountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconfig',
            name='invoice_period_days',
            field=models.PositiveIntegerField(default=3, help_text='Working day of month when the invoice for the previous billing month is generated. Used in offer text as {{invoice_period_days}}', verbose_name='Invoice Generation Working Day'),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='payment_deferral_days',
            field=models.PositiveIntegerField(default=5, help_text='Working day of month when the invoice must be paid. Used in offer text as {{payment_deferral_days}}', verbose_name='Payment Due Working Day'),
        ),
    ]
