# Generated by Django 5.2.13 on 2026-04-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_regional_policy_remove_blockingrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalblockingpolicy',
            options={'ordering': ['region_code'], 'verbose_name': 'Blocking Rule', 'verbose_name_plural': 'Blocking Rules'},
        ),
    ]
