# Generated by Django 5.2.5 on 2025-09-15 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, verbose_name='Period Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('new_registrations', models.PositiveIntegerField(default=0, verbose_name='New Registrations')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Total Users')),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Growth Rate (%)')),
                ('new_owners', models.PositiveIntegerField(default=0, verbose_name='New Owners')),
                ('new_sitters', models.PositiveIntegerField(default=0, verbose_name='New Sitters')),
                ('new_providers', models.PositiveIntegerField(default=0, verbose_name='New Providers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Growth',
                'verbose_name_plural': 'User Growth',
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, verbose_name='Period Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Total Users')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Active Users')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='New Users')),
                ('churned_users', models.PositiveIntegerField(default=0, verbose_name='Churned Users')),
                ('avg_session_duration', models.PositiveIntegerField(default=0, verbose_name='Average Session Duration (sec)')),
                ('avg_page_views', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Average Page Views')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Retention Rate (%)')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Conversion Rate (%)')),
                ('booking_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Booking Rate (%)')),
                ('payment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Payment Rate (%)')),
                ('owners_count', models.PositiveIntegerField(default=0, verbose_name='Owners Count')),
                ('sitters_count', models.PositiveIntegerField(default=0, verbose_name='Sitters Count')),
                ('providers_count', models.PositiveIntegerField(default=0, verbose_name='Providers Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Metrics',
                'verbose_name_plural': 'User Metrics',
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Login Count')),
                ('session_duration', models.PositiveIntegerField(default=0, verbose_name='Session Duration (sec)')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Page Views')),
                ('actions_count', models.PositiveIntegerField(default=0, verbose_name='Actions Count')),
                ('searches_count', models.PositiveIntegerField(default=0, verbose_name='Searches Count')),
                ('bookings_count', models.PositiveIntegerField(default=0, verbose_name='Bookings Count')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Reviews Count')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='Messages Count')),
                ('first_activity', models.DateTimeField(blank=True, null=True, verbose_name='First Activity')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-date', '-last_activity'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('registration', 'Registration'), ('profile_completion', 'Profile Completion'), ('first_search', 'First Search'), ('first_view', 'First View'), ('first_booking', 'First Booking'), ('first_payment', 'First Payment'), ('repeat_booking', 'Repeat Booking')], max_length=20, verbose_name='Conversion Stage')),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='Achieved At')),
                ('time_to_achieve', models.PositiveIntegerField(blank=True, null=True, verbose_name='Time to Achieve (hours)')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Conversion',
                'verbose_name_plural': 'User Conversions',
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'stage')},
            },
        ),
    ]
