# Generated by Django 5.2.5 on 2025-09-15 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('html_body', models.TextField(blank=True, help_text='HTML version of the email body', verbose_name='HTML Body')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=10, verbose_name='Channel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('default_enabled', models.BooleanField(default=True, verbose_name='Default Enabled')),
                ('is_required', models.BooleanField(default=False, help_text='Required notifications cannot be disabled by users', verbose_name='Is Required')),
            ],
            options={
                'verbose_name': 'Notification Type',
                'verbose_name_plural': 'Notification Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('appointment', 'Appointment'), ('medical', 'Medical'), ('system', 'System'), ('booking', 'Booking'), ('cancellation', 'Cancellation'), ('pet_sitting', 'Pet Sitting'), ('role_invite', 'Role Invite'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('in_app', 'In-App'), ('all', 'All Channels')], default='all', max_length=10, verbose_name='Channel')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_cancelled', 'Booking Cancelled'), ('booking_updated', 'Booking Updated'), ('booking_completed', 'Booking Completed'), ('price_changed', 'Price Changed'), ('review_added', 'Review Added'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('provider_blocked', 'Provider Blocked'), ('provider_unblocked', 'Provider Unblocked'), ('role_invite_sent', 'Role Invite Sent'), ('role_invite_accepted', 'Role Invite Accepted'), ('role_invite_expired', 'Role Invite Expired'), ('pet_sitting_request', 'Pet Sitting Request'), ('pet_sitting_accepted', 'Pet Sitting Accepted'), ('pet_sitting_completed', 'Pet Sitting Completed')], help_text='Type of event that triggers the notification', max_length=50, verbose_name='Event Type')),
                ('condition', models.TextField(help_text='Python expression for evaluating when to trigger the notification', verbose_name='Condition')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the notification', max_length=10, verbose_name='Priority')),
                ('channels', models.JSONField(default=list, help_text='List of delivery channels (email, push, in_app)', verbose_name='Channels')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the rule is active', verbose_name='Is Active')),
                ('inheritance', models.CharField(choices=[('global', 'Global'), ('user_specific', 'User Specific')], default='global', help_text='Global rule or user-specific override', max_length=15, verbose_name='Inheritance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking', verbose_name='Version')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_rules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('user', models.ForeignKey(blank=True, help_text='User for user-specific rules (null for global rules)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('template', models.ForeignKey(help_text='Notification template to use', on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Notification Rule',
                'verbose_name_plural': 'Notification Rules',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='notificatio_event_t_cce880_idx'), models.Index(fields=['priority'], name='notificatio_priorit_055737_idx'), models.Index(fields=['inheritance', 'user'], name='notificatio_inherit_dfa289_idx')],
                'unique_together': {('event_type', 'condition', 'template', 'inheritance', 'user')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Enabled')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push Enabled')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='In-App Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='notifications.notificationtype', verbose_name='Notification Type')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('procedure_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')], default='optional', help_text='Procedure type (mandatory/optional)', max_length=10, verbose_name='Procedure Type')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom interval')], max_length=10, verbose_name='Frequency')),
                ('interval_days', models.IntegerField(blank=True, null=True, verbose_name='Interval Days')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_notified', models.DateTimeField(blank=True, null=True, verbose_name='Last Notified')),
                ('next_notification', models.DateTimeField(blank=True, null=True, verbose_name='Next Notification')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['next_notification'],
                'indexes': [models.Index(fields=['next_notification'], name='notificatio_next_no_02a7ed_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_272217_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time_before_booking', models.PositiveIntegerField(default=120, help_text='Time in minutes before booking to send reminder', verbose_name='Reminder Time Before Booking')),
                ('multiple_reminders', models.BooleanField(default=False, help_text='Enable multiple reminders for the same booking', verbose_name='Multiple Reminders')),
                ('reminder_intervals', models.JSONField(blank=True, default=list, help_text='List of reminder intervals in minutes (e.g., [1440, 120] for 1 day and 2 hours)', verbose_name='Reminder Intervals')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these reminder settings are active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reminder Settings',
                'verbose_name_plural': 'Reminder Settings',
                'ordering': ['-updated_at'],
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking', 'Booking'), ('cancellation', 'Cancellation'), ('pet_sitting', 'Pet Sitting'), ('appointment', 'Appointment'), ('system', 'System')], max_length=20, verbose_name='Event Type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=10, verbose_name='Channel')),
                ('notification_time', models.CharField(choices=[('instant', 'Instant'), ('30min', '30 minutes before'), ('1hour', '1 hour before'), ('2hours', '2 hours before'), ('6hours', '6 hours before'), ('12hours', '12 hours before'), ('24hours', '24 hours before')], default='instant', max_length=10, verbose_name='Notification Time')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Notification Setting',
                'verbose_name_plural': 'User Notification Settings',
                'ordering': ['user', 'event_type', 'channel'],
                'unique_together': {('user', 'event_type', 'channel', 'notification_time')},
            },
        ),
    ]
