# Generated by Django 5.2.5 on 2025-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_de',
            field=models.TextField(blank=True, help_text='Body in German', verbose_name='Body (German)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_en',
            field=models.TextField(blank=True, help_text='Body in English', verbose_name='Body (English)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_me',
            field=models.TextField(blank=True, help_text='Body in Montenegrian', verbose_name='Body (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_ru',
            field=models.TextField(blank=True, help_text='Body in Russian', verbose_name='Body (Russian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='html_body_de',
            field=models.TextField(blank=True, help_text='HTML Body in German', verbose_name='HTML Body (German)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='html_body_en',
            field=models.TextField(blank=True, help_text='HTML Body in English', verbose_name='HTML Body (English)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='html_body_me',
            field=models.TextField(blank=True, help_text='HTML Body in Montenegrian', verbose_name='HTML Body (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='html_body_ru',
            field=models.TextField(blank=True, help_text='HTML Body in Russian', verbose_name='HTML Body (Russian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=100, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=100, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=100, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_de',
            field=models.CharField(blank=True, help_text='Subject in German', max_length=200, verbose_name='Subject (German)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_en',
            field=models.CharField(blank=True, help_text='Subject in English', max_length=200, verbose_name='Subject (English)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_me',
            field=models.CharField(blank=True, help_text='Subject in Montenegrian', max_length=200, verbose_name='Subject (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_ru',
            field=models.CharField(blank=True, help_text='Subject in Russian', max_length=200, verbose_name='Subject (Russian)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description in German', verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description in English', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description_me',
            field=models.TextField(blank=True, help_text='Description in Montenegrian', verbose_name='Description (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Description in Russian', verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=100, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=100, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=100, verbose_name='Name (Russian)'),
        ),
    ]
