# Generated by Django 5.2.5 on 2025-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=100, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=100, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=100, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=100, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=100, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=100, verbose_name='Name (Russian)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_de',
            field=models.TextField(blank=True, help_text='Description in German', verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description in English', verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_me',
            field=models.TextField(blank=True, help_text='Description in Montenegrian', verbose_name='Description (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Description in Russian', verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='title_de',
            field=models.CharField(blank=True, help_text='Title in German', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='title_en',
            field=models.CharField(blank=True, help_text='Title in English', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='title_me',
            field=models.CharField(blank=True, help_text='Title in Montenegrian', max_length=200, verbose_name='Title (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Title in Russian', max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_de',
            field=models.CharField(blank=True, help_text='Name in German', max_length=50, verbose_name='Name (German)'),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=50, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_me',
            field=models.CharField(blank=True, help_text='Name in Montenegrian', max_length=50, verbose_name='Name (Montenegrian)'),
        ),
        migrations.AddField(
            model_name='pettype',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Name in Russian', max_length=50, verbose_name='Name (Russian)'),
        ),
    ]
