# Generated by Django 5.2.5 on 2025-10-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_breed_name_de_breed_name_en_breed_name_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Medical conditions and history', null=True, verbose_name='Medical Conditions'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.JSONField(blank=True, default=dict, help_text='Special care requirements', null=True, verbose_name='Special Needs'),
        ),
    ]
