# Generated by Django 5.2.5 on 2025-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_medical_conditions_alter_pet_special_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the pet is active', verbose_name='Is Active'),
        ),
    ]
