# Generated by Django 5.2.5 on 2025-11-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_is_active'),
        ('providers', '0007_remove_provider_providers_p_address_e32109_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrecord',
            name='provider_location',
            field=models.ForeignKey(blank=True, help_text='Location where the service was provided', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pet_records', to='providers.providerlocation', verbose_name='Provider Location'),
        ),
        migrations.AlterField(
            model_name='petrecord',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use provider_location instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pet_records', to='providers.provider', verbose_name='Provider (Legacy)'),
        ),
    ]
