# Generated by Django 5.2.10 on 2026-02-13 09:16

import datetime
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def fill_pet_null_birth_date_and_weight(apps, schema_editor):
    """Заполняем NULL birth_date и weight у существующих Pet перед введением NOT NULL."""
    Pet = apps.get_model('pets', 'Pet')
    default_date = datetime.date(2000, 1, 1)
    default_weight = Decimal('0.00')
    Pet.objects.filter(birth_date__isnull=True).update(birth_date=default_date)
    Pet.objects.filter(weight__isnull=True).update(weight=default_weight)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_petrecord_diagnosis_petrecord_anamnesis'),
    ]

    operations = [
        migrations.RunPython(fill_pet_null_birth_date_and_weight, noop_reverse),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(help_text='Pet birth date (mandatory for weight-driven pricing)', verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Pet weight in kg (mandatory for size-based pricing)', max_digits=5, verbose_name='Weight'),
        ),
        migrations.CreateModel(
            name='SizeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], help_text='Size category: S, M, L, XL', max_length=10, verbose_name='Size Code')),
                ('min_weight_kg', models.DecimalField(decimal_places=2, help_text='Minimum weight in kg (inclusive)', max_digits=5, verbose_name='Min Weight (kg)')),
                ('max_weight_kg', models.DecimalField(decimal_places=2, help_text='Maximum weight in kg (inclusive)', max_digits=5, verbose_name='Max Weight (kg)')),
                ('pet_type', models.ForeignKey(help_text='Pet type (e.g. dog, cat)', on_delete=django.db.models.deletion.CASCADE, related_name='size_rules', to='pets.pettype', verbose_name='Pet Type')),
            ],
            options={
                'verbose_name': 'Size Rule',
                'verbose_name_plural': 'Size Rules',
                'ordering': ['pet_type', 'min_weight_kg'],
                'unique_together': {('pet_type', 'size_code')},
            },
        ),
    ]
