# Generated by Django 5.2.10 on 2026-02-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_weight_driven_pricing_sizerule_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetOwnershipInvite',
        ),
    ]
