# Generated by Django 5.2.11 on 2026-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_remove_legacy_invite_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='behavioral_traits',
            field=models.JSONField(blank=True, default=list, help_text='List of behavioral tags (e.g. flight_risk, water_fear)', verbose_name='Behavioral Traits'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', help_text='Gender of the pet (Male, Female, Unknown)', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_neutered',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', help_text='Neutering status (Yes, No, Unknown)', max_length=1, verbose_name='Is Neutered'),
        ),
    ]
