# Generated by Django 5.2.11 on 2026-03-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_pet_behavioral_traits_pet_gender_pet_is_neutered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vaccination_status',
            field=models.CharField(choices=[('full', 'Fully vaccinated'), ('partial', 'Partially vaccinated'), ('none', 'Not vaccinated'), ('unknown', 'Unknown')], default='unknown', help_text='Vaccination status (full, partial, none, unknown)', max_length=10, verbose_name='Vaccination Status'),
        ),
    ]
