# Generated by Django 5.2.11 on 2026-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_add_pet_vaccination_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for API and i18n (e.g. osteoarthritis, asthma)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Default display name', max_length=200, verbose_name='Name')),
                ('category', models.CharField(choices=[('orthopaedic', 'Orthopaedic'), ('cardio_respiratory', 'Cardiological and respiratory'), ('neurological', 'Neurological'), ('dermatological_immune', 'Dermatological and immune'), ('endocrine_systemic', 'Endocrine and systemic')], help_text='Type of chronic condition', max_length=30, verbose_name='Category')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within category', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Chronic Condition',
                'verbose_name_plural': 'Chronic Conditions',
                'ordering': ['category', 'order', 'code'],
            },
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccination_status',
        ),
        migrations.AddField(
            model_name='pet',
            name='core_vaccination_expiry',
            field=models.DateField(blank=True, help_text='Date when core/complex vaccination expires. Null = unknown.', null=True, verbose_name='Core vaccination expiry'),
        ),
        migrations.AddField(
            model_name='pet',
            name='identifier',
            field=models.CharField(blank=True, help_text='Microchip number (15 digits) or tattoo. Format depends on country.', max_length=50, null=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='pet',
            name='rabies_vaccination_expiry',
            field=models.DateField(blank=True, help_text='Date when rabies vaccination expires (next revaccination). Null = unknown.', null=True, verbose_name='Rabies vaccination expiry'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Medical conditions and history (allergies, etc.). Chronic conditions use chronic_conditions M2M.', null=True, verbose_name='Medical Conditions'),
        ),
        migrations.AddField(
            model_name='pet',
            name='chronic_conditions',
            field=models.ManyToManyField(blank=True, help_text='Standardized chronic conditions from reference list', related_name='pets', to='pets.chroniccondition', verbose_name='Chronic conditions'),
        ),
    ]
