# Generated by Django 5.2.11 on 2026-03-03 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_seed_behavioral_traits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Удаляем FK main_owner (больше не нужен)
        migrations.RemoveField(
            model_name='pet',
            name='main_owner',
        ),
        # 2. Удаляем старое M2M поле owners (без through)
        migrations.RemoveField(
            model_name='pet',
            name='owners',
        ),
        # 3. Создаём through-модель PetOwner
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main Owner'), ('coowner', 'Co-owner')], default='coowner', help_text='Owner role: main or co-owner', max_length=10, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Pet Owner',
                'verbose_name_plural': 'Pet Owners',
            },
        ),
        # 4. Добавляем новое M2M поле owners с through='PetOwner'
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(
                help_text='All owners of the pet',
                related_name='pets',
                through='pets.PetOwner',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Owners',
            ),
        ),
        # 5. Индексы и constraints
        migrations.AddIndex(
            model_name='petowner',
            index=models.Index(fields=['pet', 'role'], name='pets_petown_pet_id_a96cf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='petowner',
            constraint=models.UniqueConstraint(fields=('pet', 'user'), name='unique_pet_owner_rel'),
        ),
    ]
