# Generated by Django 5.2.11 on 2026-03-12 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sync_pet_record_file_links(apps, schema_editor):
    PetRecordFile = apps.get_model('pets', 'PetRecordFile')
    PetRecordFilesM2M = PetRecordFile.records.through

    for document in PetRecordFile.objects.all().iterator():
        linked_record_ids = list(
            PetRecordFilesM2M.objects.filter(
                petrecordfile_id=document.id,
            ).values_list('petrecord_id', flat=True)
        )
        unique_linked_record_ids = list(dict.fromkeys(linked_record_ids))

        canonical_record_id = document.pet_record_id
        if canonical_record_id is None and len(unique_linked_record_ids) == 1:
            canonical_record_id = unique_linked_record_ids[0]
            PetRecordFile.objects.filter(pk=document.pk).update(pet_record_id=canonical_record_id)

        if canonical_record_id is None:
            PetRecordFilesM2M.objects.filter(petrecordfile_id=document.id).delete()
            continue

        PetRecordFilesM2M.objects.filter(
            petrecordfile_id=document.id,
        ).exclude(
            petrecord_id=canonical_record_id,
        ).delete()
        PetRecordFilesM2M.objects.get_or_create(
            petrecord_id=canonical_record_id,
            petrecordfile_id=document.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_fix_user_fks_to_users_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Legacy Medical Record', 'verbose_name_plural': 'Legacy Medical Records'},
        ),
        migrations.AlterModelOptions(
            name='petrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Visit Record', 'verbose_name_plural': 'Visit Records'},
        ),
        migrations.CreateModel(
            name='VisitRecordAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Clinical addendum text', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(help_text='User who created the addendum', on_delete=django.db.models.deletion.PROTECT, related_name='visit_record_addenda', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('visit_record', models.ForeignKey(help_text='Visit protocol to which this addendum belongs', on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='pets.petrecord', verbose_name='Visit Record')),
            ],
            options={
                'verbose_name': 'Visit Record Addendum',
                'verbose_name_plural': 'Visit Record Addenda',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(sync_pet_record_file_links, migrations.RunPython.noop),
    ]
