# Generated by Django 5.2.11 on 2026-03-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0023_alter_documenttype_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petdocument',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the owner-space document was deactivated.', null=True, verbose_name='Deactivated At'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User who deactivated the owner-space document.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_pet_documents', to=settings.AUTH_USER_MODEL, verbose_name='Deactivated By'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='lifecycle_reason_code',
            field=models.CharField(blank=True, help_text='Optional structured reason code for deactivation or withdrawal.', max_length=100, verbose_name='Lifecycle Reason Code'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='lifecycle_reason_comment',
            field=models.TextField(blank=True, help_text='Optional comment for deactivation or withdrawal.', verbose_name='Lifecycle Reason Comment'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('withdrawn', 'Withdrawn')], default='active', help_text='Current lifecycle state of the document.', max_length=20, verbose_name='Lifecycle Status'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Optimistic lock version for concurrent document updates.', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='When the provider document was withdrawn.', null=True, verbose_name='Withdrawn At'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, help_text='User who withdrew the provider-managed document.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_pet_documents', to=settings.AUTH_USER_MODEL, verbose_name='Withdrawn By'),
        ),
        migrations.AddIndex(
            model_name='petdocument',
            index=models.Index(fields=['pet', 'lifecycle_status'], name='pets_petrec_pet_id_02ba01_idx'),
        ),
        migrations.AddIndex(
            model_name='petdocument',
            index=models.Index(fields=['visit_record', 'lifecycle_status'], name='pets_petrec_visit_r_7393c2_idx'),
        ),
    ]
